package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMPUTER_NAME.
 */
public class ComputerName {

    private int ComputerID;
    private String ComputerName;
    private int ShopID;
    private int ComputerType;
    private String IPAddress;
    private String RegistrationNumber;
    private String DeviceCode;
    private Integer KDSID;
    private String Description;
    private Integer Deleted;

    public ComputerName() {
    }

    public ComputerName(int ComputerID) {
        this.ComputerID = ComputerID;
    }

    public ComputerName(int ComputerID, String ComputerName, int ShopID, int ComputerType, String IPAddress, String RegistrationNumber, String DeviceCode, Integer KDSID, String Description, Integer Deleted) {
        this.ComputerID = ComputerID;
        this.ComputerName = ComputerName;
        this.ShopID = ShopID;
        this.ComputerType = ComputerType;
        this.IPAddress = IPAddress;
        this.RegistrationNumber = RegistrationNumber;
        this.DeviceCode = DeviceCode;
        this.KDSID = KDSID;
        this.Description = Description;
        this.Deleted = Deleted;
    }

    public int getComputerID() {
        return ComputerID;
    }

    public void setComputerID(int ComputerID) {
        this.ComputerID = ComputerID;
    }

    public String getComputerName() {
        return ComputerName;
    }

    public void setComputerName(String ComputerName) {
        this.ComputerName = ComputerName;
    }

    public int getShopID() {
        return ShopID;
    }

    public void setShopID(int ShopID) {
        this.ShopID = ShopID;
    }

    public int getComputerType() {
        return ComputerType;
    }

    public void setComputerType(int ComputerType) {
        this.ComputerType = ComputerType;
    }

    public String getIPAddress() {
        return IPAddress;
    }

    public void setIPAddress(String IPAddress) {
        this.IPAddress = IPAddress;
    }

    public String getRegistrationNumber() {
        return RegistrationNumber;
    }

    public void setRegistrationNumber(String RegistrationNumber) {
        this.RegistrationNumber = RegistrationNumber;
    }

    public String getDeviceCode() {
        return DeviceCode;
    }

    public void setDeviceCode(String DeviceCode) {
        this.DeviceCode = DeviceCode;
    }

    public Integer getKDSID() {
        return KDSID;
    }

    public void setKDSID(Integer KDSID) {
        this.KDSID = KDSID;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public Integer getDeleted() {
        return Deleted;
    }

    public void setDeleted(Integer Deleted) {
        this.Deleted = Deleted;
    }

}
