package com.vtec.j1tth4.vtecpos.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.vtec.j1tth4.vtecpos.dao.BankName;
import com.vtec.j1tth4.vtecpos.dao.ComputerName;
import com.vtec.j1tth4.vtecpos.dao.CreditCardType;
import com.vtec.j1tth4.vtecpos.dao.Document;
import com.vtec.j1tth4.vtecpos.dao.DocumentType;
import com.vtec.j1tth4.vtecpos.dao.fc_cardhistory;
import com.vtec.j1tth4.vtecpos.dao.fc_cardinfo;
import com.vtec.j1tth4.vtecpos.dao.Products;
import com.vtec.j1tth4.vtecpos.dao.ProductDept;
import com.vtec.j1tth4.vtecpos.dao.ProductGroup;
import com.vtec.j1tth4.vtecpos.dao.ProductCategory;
import com.vtec.j1tth4.vtecpos.dao.ProductComponent;
import com.vtec.j1tth4.vtecpos.dao.ProductComponentGroup;
import com.vtec.j1tth4.vtecpos.dao.ProductPrice;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroup;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupData;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupDate;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupShop;
import com.vtec.j1tth4.vtecpos.dao.ProductType;
import com.vtec.j1tth4.vtecpos.dao.ProductVat;
import com.vtec.j1tth4.vtecpos.dao.ShopCategory;
import com.vtec.j1tth4.vtecpos.dao.ShopData;
import com.vtec.j1tth4.vtecpos.dao.OrderTransaction;
import com.vtec.j1tth4.vtecpos.dao.OrderDetail;
import com.vtec.j1tth4.vtecpos.dao.OrderPayDetail;
import com.vtec.j1tth4.vtecpos.dao.Staffs;
import com.vtec.j1tth4.vtecpos.dao.StaffRole;
import com.vtec.j1tth4.vtecpos.dao.Session;
import com.vtec.j1tth4.vtecpos.dao.SessionEnddayDetail;

import com.vtec.j1tth4.vtecpos.dao.BankNameDao;
import com.vtec.j1tth4.vtecpos.dao.ComputerNameDao;
import com.vtec.j1tth4.vtecpos.dao.CreditCardTypeDao;
import com.vtec.j1tth4.vtecpos.dao.DocumentDao;
import com.vtec.j1tth4.vtecpos.dao.DocumentTypeDao;
import com.vtec.j1tth4.vtecpos.dao.fc_cardhistoryDao;
import com.vtec.j1tth4.vtecpos.dao.fc_cardinfoDao;
import com.vtec.j1tth4.vtecpos.dao.ProductsDao;
import com.vtec.j1tth4.vtecpos.dao.ProductDeptDao;
import com.vtec.j1tth4.vtecpos.dao.ProductGroupDao;
import com.vtec.j1tth4.vtecpos.dao.ProductCategoryDao;
import com.vtec.j1tth4.vtecpos.dao.ProductComponentDao;
import com.vtec.j1tth4.vtecpos.dao.ProductComponentGroupDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupDataDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupDateDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupShopDao;
import com.vtec.j1tth4.vtecpos.dao.ProductTypeDao;
import com.vtec.j1tth4.vtecpos.dao.ProductVatDao;
import com.vtec.j1tth4.vtecpos.dao.ShopCategoryDao;
import com.vtec.j1tth4.vtecpos.dao.ShopDataDao;
import com.vtec.j1tth4.vtecpos.dao.OrderTransactionDao;
import com.vtec.j1tth4.vtecpos.dao.OrderDetailDao;
import com.vtec.j1tth4.vtecpos.dao.OrderPayDetailDao;
import com.vtec.j1tth4.vtecpos.dao.StaffsDao;
import com.vtec.j1tth4.vtecpos.dao.StaffRoleDao;
import com.vtec.j1tth4.vtecpos.dao.SessionDao;
import com.vtec.j1tth4.vtecpos.dao.SessionEnddayDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bankNameDaoConfig;
    private final DaoConfig computerNameDaoConfig;
    private final DaoConfig creditCardTypeDaoConfig;
    private final DaoConfig documentDaoConfig;
    private final DaoConfig documentTypeDaoConfig;
    private final DaoConfig fc_cardhistoryDaoConfig;
    private final DaoConfig fc_cardinfoDaoConfig;
    private final DaoConfig productsDaoConfig;
    private final DaoConfig productDeptDaoConfig;
    private final DaoConfig productGroupDaoConfig;
    private final DaoConfig productCategoryDaoConfig;
    private final DaoConfig productComponentDaoConfig;
    private final DaoConfig productComponentGroupDaoConfig;
    private final DaoConfig productPriceDaoConfig;
    private final DaoConfig productPriceGroupDaoConfig;
    private final DaoConfig productPriceGroupDataDaoConfig;
    private final DaoConfig productPriceGroupDateDaoConfig;
    private final DaoConfig productPriceGroupShopDaoConfig;
    private final DaoConfig productTypeDaoConfig;
    private final DaoConfig productVatDaoConfig;
    private final DaoConfig shopCategoryDaoConfig;
    private final DaoConfig shopDataDaoConfig;
    private final DaoConfig orderTransactionDaoConfig;
    private final DaoConfig orderDetailDaoConfig;
    private final DaoConfig orderPayDetailDaoConfig;
    private final DaoConfig staffsDaoConfig;
    private final DaoConfig staffRoleDaoConfig;
    private final DaoConfig sessionDaoConfig;
    private final DaoConfig sessionEnddayDetailDaoConfig;

    private final BankNameDao bankNameDao;
    private final ComputerNameDao computerNameDao;
    private final CreditCardTypeDao creditCardTypeDao;
    private final DocumentDao documentDao;
    private final DocumentTypeDao documentTypeDao;
    private final fc_cardhistoryDao fc_cardhistoryDao;
    private final fc_cardinfoDao fc_cardinfoDao;
    private final ProductsDao productsDao;
    private final ProductDeptDao productDeptDao;
    private final ProductGroupDao productGroupDao;
    private final ProductCategoryDao productCategoryDao;
    private final ProductComponentDao productComponentDao;
    private final ProductComponentGroupDao productComponentGroupDao;
    private final ProductPriceDao productPriceDao;
    private final ProductPriceGroupDao productPriceGroupDao;
    private final ProductPriceGroupDataDao productPriceGroupDataDao;
    private final ProductPriceGroupDateDao productPriceGroupDateDao;
    private final ProductPriceGroupShopDao productPriceGroupShopDao;
    private final ProductTypeDao productTypeDao;
    private final ProductVatDao productVatDao;
    private final ShopCategoryDao shopCategoryDao;
    private final ShopDataDao shopDataDao;
    private final OrderTransactionDao orderTransactionDao;
    private final OrderDetailDao orderDetailDao;
    private final OrderPayDetailDao orderPayDetailDao;
    private final StaffsDao staffsDao;
    private final StaffRoleDao staffRoleDao;
    private final SessionDao sessionDao;
    private final SessionEnddayDetailDao sessionEnddayDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bankNameDaoConfig = daoConfigMap.get(BankNameDao.class).clone();
        bankNameDaoConfig.initIdentityScope(type);

        computerNameDaoConfig = daoConfigMap.get(ComputerNameDao.class).clone();
        computerNameDaoConfig.initIdentityScope(type);

        creditCardTypeDaoConfig = daoConfigMap.get(CreditCardTypeDao.class).clone();
        creditCardTypeDaoConfig.initIdentityScope(type);

        documentDaoConfig = daoConfigMap.get(DocumentDao.class).clone();
        documentDaoConfig.initIdentityScope(type);

        documentTypeDaoConfig = daoConfigMap.get(DocumentTypeDao.class).clone();
        documentTypeDaoConfig.initIdentityScope(type);

        fc_cardhistoryDaoConfig = daoConfigMap.get(fc_cardhistoryDao.class).clone();
        fc_cardhistoryDaoConfig.initIdentityScope(type);

        fc_cardinfoDaoConfig = daoConfigMap.get(fc_cardinfoDao.class).clone();
        fc_cardinfoDaoConfig.initIdentityScope(type);

        productsDaoConfig = daoConfigMap.get(ProductsDao.class).clone();
        productsDaoConfig.initIdentityScope(type);

        productDeptDaoConfig = daoConfigMap.get(ProductDeptDao.class).clone();
        productDeptDaoConfig.initIdentityScope(type);

        productGroupDaoConfig = daoConfigMap.get(ProductGroupDao.class).clone();
        productGroupDaoConfig.initIdentityScope(type);

        productCategoryDaoConfig = daoConfigMap.get(ProductCategoryDao.class).clone();
        productCategoryDaoConfig.initIdentityScope(type);

        productComponentDaoConfig = daoConfigMap.get(ProductComponentDao.class).clone();
        productComponentDaoConfig.initIdentityScope(type);

        productComponentGroupDaoConfig = daoConfigMap.get(ProductComponentGroupDao.class).clone();
        productComponentGroupDaoConfig.initIdentityScope(type);

        productPriceDaoConfig = daoConfigMap.get(ProductPriceDao.class).clone();
        productPriceDaoConfig.initIdentityScope(type);

        productPriceGroupDaoConfig = daoConfigMap.get(ProductPriceGroupDao.class).clone();
        productPriceGroupDaoConfig.initIdentityScope(type);

        productPriceGroupDataDaoConfig = daoConfigMap.get(ProductPriceGroupDataDao.class).clone();
        productPriceGroupDataDaoConfig.initIdentityScope(type);

        productPriceGroupDateDaoConfig = daoConfigMap.get(ProductPriceGroupDateDao.class).clone();
        productPriceGroupDateDaoConfig.initIdentityScope(type);

        productPriceGroupShopDaoConfig = daoConfigMap.get(ProductPriceGroupShopDao.class).clone();
        productPriceGroupShopDaoConfig.initIdentityScope(type);

        productTypeDaoConfig = daoConfigMap.get(ProductTypeDao.class).clone();
        productTypeDaoConfig.initIdentityScope(type);

        productVatDaoConfig = daoConfigMap.get(ProductVatDao.class).clone();
        productVatDaoConfig.initIdentityScope(type);

        shopCategoryDaoConfig = daoConfigMap.get(ShopCategoryDao.class).clone();
        shopCategoryDaoConfig.initIdentityScope(type);

        shopDataDaoConfig = daoConfigMap.get(ShopDataDao.class).clone();
        shopDataDaoConfig.initIdentityScope(type);

        orderTransactionDaoConfig = daoConfigMap.get(OrderTransactionDao.class).clone();
        orderTransactionDaoConfig.initIdentityScope(type);

        orderDetailDaoConfig = daoConfigMap.get(OrderDetailDao.class).clone();
        orderDetailDaoConfig.initIdentityScope(type);

        orderPayDetailDaoConfig = daoConfigMap.get(OrderPayDetailDao.class).clone();
        orderPayDetailDaoConfig.initIdentityScope(type);

        staffsDaoConfig = daoConfigMap.get(StaffsDao.class).clone();
        staffsDaoConfig.initIdentityScope(type);

        staffRoleDaoConfig = daoConfigMap.get(StaffRoleDao.class).clone();
        staffRoleDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        sessionEnddayDetailDaoConfig = daoConfigMap.get(SessionEnddayDetailDao.class).clone();
        sessionEnddayDetailDaoConfig.initIdentityScope(type);

        bankNameDao = new BankNameDao(bankNameDaoConfig, this);
        computerNameDao = new ComputerNameDao(computerNameDaoConfig, this);
        creditCardTypeDao = new CreditCardTypeDao(creditCardTypeDaoConfig, this);
        documentDao = new DocumentDao(documentDaoConfig, this);
        documentTypeDao = new DocumentTypeDao(documentTypeDaoConfig, this);
        fc_cardhistoryDao = new fc_cardhistoryDao(fc_cardhistoryDaoConfig, this);
        fc_cardinfoDao = new fc_cardinfoDao(fc_cardinfoDaoConfig, this);
        productsDao = new ProductsDao(productsDaoConfig, this);
        productDeptDao = new ProductDeptDao(productDeptDaoConfig, this);
        productGroupDao = new ProductGroupDao(productGroupDaoConfig, this);
        productCategoryDao = new ProductCategoryDao(productCategoryDaoConfig, this);
        productComponentDao = new ProductComponentDao(productComponentDaoConfig, this);
        productComponentGroupDao = new ProductComponentGroupDao(productComponentGroupDaoConfig, this);
        productPriceDao = new ProductPriceDao(productPriceDaoConfig, this);
        productPriceGroupDao = new ProductPriceGroupDao(productPriceGroupDaoConfig, this);
        productPriceGroupDataDao = new ProductPriceGroupDataDao(productPriceGroupDataDaoConfig, this);
        productPriceGroupDateDao = new ProductPriceGroupDateDao(productPriceGroupDateDaoConfig, this);
        productPriceGroupShopDao = new ProductPriceGroupShopDao(productPriceGroupShopDaoConfig, this);
        productTypeDao = new ProductTypeDao(productTypeDaoConfig, this);
        productVatDao = new ProductVatDao(productVatDaoConfig, this);
        shopCategoryDao = new ShopCategoryDao(shopCategoryDaoConfig, this);
        shopDataDao = new ShopDataDao(shopDataDaoConfig, this);
        orderTransactionDao = new OrderTransactionDao(orderTransactionDaoConfig, this);
        orderDetailDao = new OrderDetailDao(orderDetailDaoConfig, this);
        orderPayDetailDao = new OrderPayDetailDao(orderPayDetailDaoConfig, this);
        staffsDao = new StaffsDao(staffsDaoConfig, this);
        staffRoleDao = new StaffRoleDao(staffRoleDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);
        sessionEnddayDetailDao = new SessionEnddayDetailDao(sessionEnddayDetailDaoConfig, this);

        registerDao(BankName.class, bankNameDao);
        registerDao(ComputerName.class, computerNameDao);
        registerDao(CreditCardType.class, creditCardTypeDao);
        registerDao(Document.class, documentDao);
        registerDao(DocumentType.class, documentTypeDao);
        registerDao(fc_cardhistory.class, fc_cardhistoryDao);
        registerDao(fc_cardinfo.class, fc_cardinfoDao);
        registerDao(Products.class, productsDao);
        registerDao(ProductDept.class, productDeptDao);
        registerDao(ProductGroup.class, productGroupDao);
        registerDao(ProductCategory.class, productCategoryDao);
        registerDao(ProductComponent.class, productComponentDao);
        registerDao(ProductComponentGroup.class, productComponentGroupDao);
        registerDao(ProductPrice.class, productPriceDao);
        registerDao(ProductPriceGroup.class, productPriceGroupDao);
        registerDao(ProductPriceGroupData.class, productPriceGroupDataDao);
        registerDao(ProductPriceGroupDate.class, productPriceGroupDateDao);
        registerDao(ProductPriceGroupShop.class, productPriceGroupShopDao);
        registerDao(ProductType.class, productTypeDao);
        registerDao(ProductVat.class, productVatDao);
        registerDao(ShopCategory.class, shopCategoryDao);
        registerDao(ShopData.class, shopDataDao);
        registerDao(OrderTransaction.class, orderTransactionDao);
        registerDao(OrderDetail.class, orderDetailDao);
        registerDao(OrderPayDetail.class, orderPayDetailDao);
        registerDao(Staffs.class, staffsDao);
        registerDao(StaffRole.class, staffRoleDao);
        registerDao(Session.class, sessionDao);
        registerDao(SessionEnddayDetail.class, sessionEnddayDetailDao);
    }
    
    public void clear() {
        bankNameDaoConfig.getIdentityScope().clear();
        computerNameDaoConfig.getIdentityScope().clear();
        creditCardTypeDaoConfig.getIdentityScope().clear();
        documentDaoConfig.getIdentityScope().clear();
        documentTypeDaoConfig.getIdentityScope().clear();
        fc_cardhistoryDaoConfig.getIdentityScope().clear();
        fc_cardinfoDaoConfig.getIdentityScope().clear();
        productsDaoConfig.getIdentityScope().clear();
        productDeptDaoConfig.getIdentityScope().clear();
        productGroupDaoConfig.getIdentityScope().clear();
        productCategoryDaoConfig.getIdentityScope().clear();
        productComponentDaoConfig.getIdentityScope().clear();
        productComponentGroupDaoConfig.getIdentityScope().clear();
        productPriceDaoConfig.getIdentityScope().clear();
        productPriceGroupDaoConfig.getIdentityScope().clear();
        productPriceGroupDataDaoConfig.getIdentityScope().clear();
        productPriceGroupDateDaoConfig.getIdentityScope().clear();
        productPriceGroupShopDaoConfig.getIdentityScope().clear();
        productTypeDaoConfig.getIdentityScope().clear();
        productVatDaoConfig.getIdentityScope().clear();
        shopCategoryDaoConfig.getIdentityScope().clear();
        shopDataDaoConfig.getIdentityScope().clear();
        orderTransactionDaoConfig.getIdentityScope().clear();
        orderDetailDaoConfig.getIdentityScope().clear();
        orderPayDetailDaoConfig.getIdentityScope().clear();
        staffsDaoConfig.getIdentityScope().clear();
        staffRoleDaoConfig.getIdentityScope().clear();
        sessionDaoConfig.getIdentityScope().clear();
        sessionEnddayDetailDaoConfig.getIdentityScope().clear();
    }

    public BankNameDao getBankNameDao() {
        return bankNameDao;
    }

    public ComputerNameDao getComputerNameDao() {
        return computerNameDao;
    }

    public CreditCardTypeDao getCreditCardTypeDao() {
        return creditCardTypeDao;
    }

    public DocumentDao getDocumentDao() {
        return documentDao;
    }

    public DocumentTypeDao getDocumentTypeDao() {
        return documentTypeDao;
    }

    public fc_cardhistoryDao getFc_cardhistoryDao() {
        return fc_cardhistoryDao;
    }

    public fc_cardinfoDao getFc_cardinfoDao() {
        return fc_cardinfoDao;
    }

    public ProductsDao getProductsDao() {
        return productsDao;
    }

    public ProductDeptDao getProductDeptDao() {
        return productDeptDao;
    }

    public ProductGroupDao getProductGroupDao() {
        return productGroupDao;
    }

    public ProductCategoryDao getProductCategoryDao() {
        return productCategoryDao;
    }

    public ProductComponentDao getProductComponentDao() {
        return productComponentDao;
    }

    public ProductComponentGroupDao getProductComponentGroupDao() {
        return productComponentGroupDao;
    }

    public ProductPriceDao getProductPriceDao() {
        return productPriceDao;
    }

    public ProductPriceGroupDao getProductPriceGroupDao() {
        return productPriceGroupDao;
    }

    public ProductPriceGroupDataDao getProductPriceGroupDataDao() {
        return productPriceGroupDataDao;
    }

    public ProductPriceGroupDateDao getProductPriceGroupDateDao() {
        return productPriceGroupDateDao;
    }

    public ProductPriceGroupShopDao getProductPriceGroupShopDao() {
        return productPriceGroupShopDao;
    }

    public ProductTypeDao getProductTypeDao() {
        return productTypeDao;
    }

    public ProductVatDao getProductVatDao() {
        return productVatDao;
    }

    public ShopCategoryDao getShopCategoryDao() {
        return shopCategoryDao;
    }

    public ShopDataDao getShopDataDao() {
        return shopDataDao;
    }

    public OrderTransactionDao getOrderTransactionDao() {
        return orderTransactionDao;
    }

    public OrderDetailDao getOrderDetailDao() {
        return orderDetailDao;
    }

    public OrderPayDetailDao getOrderPayDetailDao() {
        return orderPayDetailDao;
    }

    public StaffsDao getStaffsDao() {
        return staffsDao;
    }

    public StaffRoleDao getStaffRoleDao() {
        return staffRoleDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public SessionEnddayDetailDao getSessionEnddayDetailDao() {
        return sessionEnddayDetailDao;
    }

}
