package com.vtec.j1tth4.vtecpos.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.vtec.j1tth4.vtecpos.dao.BankName;
import com.vtec.j1tth4.vtecpos.dao.ComputerName;
import com.vtec.j1tth4.vtecpos.dao.CreditCardType;
import com.vtec.j1tth4.vtecpos.dao.Document;
import com.vtec.j1tth4.vtecpos.dao.Documenttype;
import com.vtec.j1tth4.vtecpos.dao.FcCardHistory;
import com.vtec.j1tth4.vtecpos.dao.FcCardInfo;
import com.vtec.j1tth4.vtecpos.dao.FcTranDetail;
import com.vtec.j1tth4.vtecpos.dao.FcTranPayment;
import com.vtec.j1tth4.vtecpos.dao.FcTransaction;
import com.vtec.j1tth4.vtecpos.dao.Language;
import com.vtec.j1tth4.vtecpos.dao.LogAccessInfo;
import com.vtec.j1tth4.vtecpos.dao.OrderDetail;
import com.vtec.j1tth4.vtecpos.dao.OrderpayDetail;
import com.vtec.j1tth4.vtecpos.dao.OrderPrintJob;
import com.vtec.j1tth4.vtecpos.dao.OrderTransaction;
import com.vtec.j1tth4.vtecpos.dao.Products;
import com.vtec.j1tth4.vtecpos.dao.ProductDept;
import com.vtec.j1tth4.vtecpos.dao.ProductGroup;
import com.vtec.j1tth4.vtecpos.dao.ProductCategory;
import com.vtec.j1tth4.vtecpos.dao.ProductComponent;
import com.vtec.j1tth4.vtecpos.dao.ProductComponentGroup;
import com.vtec.j1tth4.vtecpos.dao.ProductPrice;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroup;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupData;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupDate;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupShop;
import com.vtec.j1tth4.vtecpos.dao.ProductType;
import com.vtec.j1tth4.vtecpos.dao.ProductVat;
import com.vtec.j1tth4.vtecpos.dao.ProgramProperty;
import com.vtec.j1tth4.vtecpos.dao.ProgramPropertyValue;
import com.vtec.j1tth4.vtecpos.dao.ShopCategory;
import com.vtec.j1tth4.vtecpos.dao.ShopData;
import com.vtec.j1tth4.vtecpos.dao.Staffs;
import com.vtec.j1tth4.vtecpos.dao.StaffRole;
import com.vtec.j1tth4.vtecpos.dao.Session;
import com.vtec.j1tth4.vtecpos.dao.SessionEnddayDetail;
import com.vtec.j1tth4.vtecpos.dao.SaleMode;

import com.vtec.j1tth4.vtecpos.dao.BankNameDao;
import com.vtec.j1tth4.vtecpos.dao.ComputerNameDao;
import com.vtec.j1tth4.vtecpos.dao.CreditCardTypeDao;
import com.vtec.j1tth4.vtecpos.dao.DocumentDao;
import com.vtec.j1tth4.vtecpos.dao.DocumenttypeDao;
import com.vtec.j1tth4.vtecpos.dao.FcCardHistoryDao;
import com.vtec.j1tth4.vtecpos.dao.FcCardInfoDao;
import com.vtec.j1tth4.vtecpos.dao.FcTranDetailDao;
import com.vtec.j1tth4.vtecpos.dao.FcTranPaymentDao;
import com.vtec.j1tth4.vtecpos.dao.FcTransactionDao;
import com.vtec.j1tth4.vtecpos.dao.LanguageDao;
import com.vtec.j1tth4.vtecpos.dao.LogAccessInfoDao;
import com.vtec.j1tth4.vtecpos.dao.OrderDetailDao;
import com.vtec.j1tth4.vtecpos.dao.OrderpayDetailDao;
import com.vtec.j1tth4.vtecpos.dao.OrderPrintJobDao;
import com.vtec.j1tth4.vtecpos.dao.OrderTransactionDao;
import com.vtec.j1tth4.vtecpos.dao.ProductsDao;
import com.vtec.j1tth4.vtecpos.dao.ProductDeptDao;
import com.vtec.j1tth4.vtecpos.dao.ProductGroupDao;
import com.vtec.j1tth4.vtecpos.dao.ProductCategoryDao;
import com.vtec.j1tth4.vtecpos.dao.ProductComponentDao;
import com.vtec.j1tth4.vtecpos.dao.ProductComponentGroupDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupDataDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupDateDao;
import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupShopDao;
import com.vtec.j1tth4.vtecpos.dao.ProductTypeDao;
import com.vtec.j1tth4.vtecpos.dao.ProductVatDao;
import com.vtec.j1tth4.vtecpos.dao.ProgramPropertyDao;
import com.vtec.j1tth4.vtecpos.dao.ProgramPropertyValueDao;
import com.vtec.j1tth4.vtecpos.dao.ShopCategoryDao;
import com.vtec.j1tth4.vtecpos.dao.ShopDataDao;
import com.vtec.j1tth4.vtecpos.dao.StaffsDao;
import com.vtec.j1tth4.vtecpos.dao.StaffRoleDao;
import com.vtec.j1tth4.vtecpos.dao.SessionDao;
import com.vtec.j1tth4.vtecpos.dao.SessionEnddayDetailDao;
import com.vtec.j1tth4.vtecpos.dao.SaleModeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bankNameDaoConfig;
    private final DaoConfig computerNameDaoConfig;
    private final DaoConfig creditCardTypeDaoConfig;
    private final DaoConfig documentDaoConfig;
    private final DaoConfig documenttypeDaoConfig;
    private final DaoConfig fcCardHistoryDaoConfig;
    private final DaoConfig fcCardInfoDaoConfig;
    private final DaoConfig fcTranDetailDaoConfig;
    private final DaoConfig fcTranPaymentDaoConfig;
    private final DaoConfig fcTransactionDaoConfig;
    private final DaoConfig languageDaoConfig;
    private final DaoConfig logAccessInfoDaoConfig;
    private final DaoConfig orderDetailDaoConfig;
    private final DaoConfig orderpayDetailDaoConfig;
    private final DaoConfig orderPrintJobDaoConfig;
    private final DaoConfig orderTransactionDaoConfig;
    private final DaoConfig productsDaoConfig;
    private final DaoConfig productDeptDaoConfig;
    private final DaoConfig productGroupDaoConfig;
    private final DaoConfig productCategoryDaoConfig;
    private final DaoConfig productComponentDaoConfig;
    private final DaoConfig productComponentGroupDaoConfig;
    private final DaoConfig productPriceDaoConfig;
    private final DaoConfig productPriceGroupDaoConfig;
    private final DaoConfig productPriceGroupDataDaoConfig;
    private final DaoConfig productPriceGroupDateDaoConfig;
    private final DaoConfig productPriceGroupShopDaoConfig;
    private final DaoConfig productTypeDaoConfig;
    private final DaoConfig productVatDaoConfig;
    private final DaoConfig programPropertyDaoConfig;
    private final DaoConfig programPropertyValueDaoConfig;
    private final DaoConfig shopCategoryDaoConfig;
    private final DaoConfig shopDataDaoConfig;
    private final DaoConfig staffsDaoConfig;
    private final DaoConfig staffRoleDaoConfig;
    private final DaoConfig sessionDaoConfig;
    private final DaoConfig sessionEnddayDetailDaoConfig;
    private final DaoConfig saleModeDaoConfig;

    private final BankNameDao bankNameDao;
    private final ComputerNameDao computerNameDao;
    private final CreditCardTypeDao creditCardTypeDao;
    private final DocumentDao documentDao;
    private final DocumenttypeDao documenttypeDao;
    private final FcCardHistoryDao fcCardHistoryDao;
    private final FcCardInfoDao fcCardInfoDao;
    private final FcTranDetailDao fcTranDetailDao;
    private final FcTranPaymentDao fcTranPaymentDao;
    private final FcTransactionDao fcTransactionDao;
    private final LanguageDao languageDao;
    private final LogAccessInfoDao logAccessInfoDao;
    private final OrderDetailDao orderDetailDao;
    private final OrderpayDetailDao orderpayDetailDao;
    private final OrderPrintJobDao orderPrintJobDao;
    private final OrderTransactionDao orderTransactionDao;
    private final ProductsDao productsDao;
    private final ProductDeptDao productDeptDao;
    private final ProductGroupDao productGroupDao;
    private final ProductCategoryDao productCategoryDao;
    private final ProductComponentDao productComponentDao;
    private final ProductComponentGroupDao productComponentGroupDao;
    private final ProductPriceDao productPriceDao;
    private final ProductPriceGroupDao productPriceGroupDao;
    private final ProductPriceGroupDataDao productPriceGroupDataDao;
    private final ProductPriceGroupDateDao productPriceGroupDateDao;
    private final ProductPriceGroupShopDao productPriceGroupShopDao;
    private final ProductTypeDao productTypeDao;
    private final ProductVatDao productVatDao;
    private final ProgramPropertyDao programPropertyDao;
    private final ProgramPropertyValueDao programPropertyValueDao;
    private final ShopCategoryDao shopCategoryDao;
    private final ShopDataDao shopDataDao;
    private final StaffsDao staffsDao;
    private final StaffRoleDao staffRoleDao;
    private final SessionDao sessionDao;
    private final SessionEnddayDetailDao sessionEnddayDetailDao;
    private final SaleModeDao saleModeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bankNameDaoConfig = daoConfigMap.get(BankNameDao.class).clone();
        bankNameDaoConfig.initIdentityScope(type);

        computerNameDaoConfig = daoConfigMap.get(ComputerNameDao.class).clone();
        computerNameDaoConfig.initIdentityScope(type);

        creditCardTypeDaoConfig = daoConfigMap.get(CreditCardTypeDao.class).clone();
        creditCardTypeDaoConfig.initIdentityScope(type);

        documentDaoConfig = daoConfigMap.get(DocumentDao.class).clone();
        documentDaoConfig.initIdentityScope(type);

        documenttypeDaoConfig = daoConfigMap.get(DocumenttypeDao.class).clone();
        documenttypeDaoConfig.initIdentityScope(type);

        fcCardHistoryDaoConfig = daoConfigMap.get(FcCardHistoryDao.class).clone();
        fcCardHistoryDaoConfig.initIdentityScope(type);

        fcCardInfoDaoConfig = daoConfigMap.get(FcCardInfoDao.class).clone();
        fcCardInfoDaoConfig.initIdentityScope(type);

        fcTranDetailDaoConfig = daoConfigMap.get(FcTranDetailDao.class).clone();
        fcTranDetailDaoConfig.initIdentityScope(type);

        fcTranPaymentDaoConfig = daoConfigMap.get(FcTranPaymentDao.class).clone();
        fcTranPaymentDaoConfig.initIdentityScope(type);

        fcTransactionDaoConfig = daoConfigMap.get(FcTransactionDao.class).clone();
        fcTransactionDaoConfig.initIdentityScope(type);

        languageDaoConfig = daoConfigMap.get(LanguageDao.class).clone();
        languageDaoConfig.initIdentityScope(type);

        logAccessInfoDaoConfig = daoConfigMap.get(LogAccessInfoDao.class).clone();
        logAccessInfoDaoConfig.initIdentityScope(type);

        orderDetailDaoConfig = daoConfigMap.get(OrderDetailDao.class).clone();
        orderDetailDaoConfig.initIdentityScope(type);

        orderpayDetailDaoConfig = daoConfigMap.get(OrderpayDetailDao.class).clone();
        orderpayDetailDaoConfig.initIdentityScope(type);

        orderPrintJobDaoConfig = daoConfigMap.get(OrderPrintJobDao.class).clone();
        orderPrintJobDaoConfig.initIdentityScope(type);

        orderTransactionDaoConfig = daoConfigMap.get(OrderTransactionDao.class).clone();
        orderTransactionDaoConfig.initIdentityScope(type);

        productsDaoConfig = daoConfigMap.get(ProductsDao.class).clone();
        productsDaoConfig.initIdentityScope(type);

        productDeptDaoConfig = daoConfigMap.get(ProductDeptDao.class).clone();
        productDeptDaoConfig.initIdentityScope(type);

        productGroupDaoConfig = daoConfigMap.get(ProductGroupDao.class).clone();
        productGroupDaoConfig.initIdentityScope(type);

        productCategoryDaoConfig = daoConfigMap.get(ProductCategoryDao.class).clone();
        productCategoryDaoConfig.initIdentityScope(type);

        productComponentDaoConfig = daoConfigMap.get(ProductComponentDao.class).clone();
        productComponentDaoConfig.initIdentityScope(type);

        productComponentGroupDaoConfig = daoConfigMap.get(ProductComponentGroupDao.class).clone();
        productComponentGroupDaoConfig.initIdentityScope(type);

        productPriceDaoConfig = daoConfigMap.get(ProductPriceDao.class).clone();
        productPriceDaoConfig.initIdentityScope(type);

        productPriceGroupDaoConfig = daoConfigMap.get(ProductPriceGroupDao.class).clone();
        productPriceGroupDaoConfig.initIdentityScope(type);

        productPriceGroupDataDaoConfig = daoConfigMap.get(ProductPriceGroupDataDao.class).clone();
        productPriceGroupDataDaoConfig.initIdentityScope(type);

        productPriceGroupDateDaoConfig = daoConfigMap.get(ProductPriceGroupDateDao.class).clone();
        productPriceGroupDateDaoConfig.initIdentityScope(type);

        productPriceGroupShopDaoConfig = daoConfigMap.get(ProductPriceGroupShopDao.class).clone();
        productPriceGroupShopDaoConfig.initIdentityScope(type);

        productTypeDaoConfig = daoConfigMap.get(ProductTypeDao.class).clone();
        productTypeDaoConfig.initIdentityScope(type);

        productVatDaoConfig = daoConfigMap.get(ProductVatDao.class).clone();
        productVatDaoConfig.initIdentityScope(type);

        programPropertyDaoConfig = daoConfigMap.get(ProgramPropertyDao.class).clone();
        programPropertyDaoConfig.initIdentityScope(type);

        programPropertyValueDaoConfig = daoConfigMap.get(ProgramPropertyValueDao.class).clone();
        programPropertyValueDaoConfig.initIdentityScope(type);

        shopCategoryDaoConfig = daoConfigMap.get(ShopCategoryDao.class).clone();
        shopCategoryDaoConfig.initIdentityScope(type);

        shopDataDaoConfig = daoConfigMap.get(ShopDataDao.class).clone();
        shopDataDaoConfig.initIdentityScope(type);

        staffsDaoConfig = daoConfigMap.get(StaffsDao.class).clone();
        staffsDaoConfig.initIdentityScope(type);

        staffRoleDaoConfig = daoConfigMap.get(StaffRoleDao.class).clone();
        staffRoleDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        sessionEnddayDetailDaoConfig = daoConfigMap.get(SessionEnddayDetailDao.class).clone();
        sessionEnddayDetailDaoConfig.initIdentityScope(type);

        saleModeDaoConfig = daoConfigMap.get(SaleModeDao.class).clone();
        saleModeDaoConfig.initIdentityScope(type);

        bankNameDao = new BankNameDao(bankNameDaoConfig, this);
        computerNameDao = new ComputerNameDao(computerNameDaoConfig, this);
        creditCardTypeDao = new CreditCardTypeDao(creditCardTypeDaoConfig, this);
        documentDao = new DocumentDao(documentDaoConfig, this);
        documenttypeDao = new DocumenttypeDao(documenttypeDaoConfig, this);
        fcCardHistoryDao = new FcCardHistoryDao(fcCardHistoryDaoConfig, this);
        fcCardInfoDao = new FcCardInfoDao(fcCardInfoDaoConfig, this);
        fcTranDetailDao = new FcTranDetailDao(fcTranDetailDaoConfig, this);
        fcTranPaymentDao = new FcTranPaymentDao(fcTranPaymentDaoConfig, this);
        fcTransactionDao = new FcTransactionDao(fcTransactionDaoConfig, this);
        languageDao = new LanguageDao(languageDaoConfig, this);
        logAccessInfoDao = new LogAccessInfoDao(logAccessInfoDaoConfig, this);
        orderDetailDao = new OrderDetailDao(orderDetailDaoConfig, this);
        orderpayDetailDao = new OrderpayDetailDao(orderpayDetailDaoConfig, this);
        orderPrintJobDao = new OrderPrintJobDao(orderPrintJobDaoConfig, this);
        orderTransactionDao = new OrderTransactionDao(orderTransactionDaoConfig, this);
        productsDao = new ProductsDao(productsDaoConfig, this);
        productDeptDao = new ProductDeptDao(productDeptDaoConfig, this);
        productGroupDao = new ProductGroupDao(productGroupDaoConfig, this);
        productCategoryDao = new ProductCategoryDao(productCategoryDaoConfig, this);
        productComponentDao = new ProductComponentDao(productComponentDaoConfig, this);
        productComponentGroupDao = new ProductComponentGroupDao(productComponentGroupDaoConfig, this);
        productPriceDao = new ProductPriceDao(productPriceDaoConfig, this);
        productPriceGroupDao = new ProductPriceGroupDao(productPriceGroupDaoConfig, this);
        productPriceGroupDataDao = new ProductPriceGroupDataDao(productPriceGroupDataDaoConfig, this);
        productPriceGroupDateDao = new ProductPriceGroupDateDao(productPriceGroupDateDaoConfig, this);
        productPriceGroupShopDao = new ProductPriceGroupShopDao(productPriceGroupShopDaoConfig, this);
        productTypeDao = new ProductTypeDao(productTypeDaoConfig, this);
        productVatDao = new ProductVatDao(productVatDaoConfig, this);
        programPropertyDao = new ProgramPropertyDao(programPropertyDaoConfig, this);
        programPropertyValueDao = new ProgramPropertyValueDao(programPropertyValueDaoConfig, this);
        shopCategoryDao = new ShopCategoryDao(shopCategoryDaoConfig, this);
        shopDataDao = new ShopDataDao(shopDataDaoConfig, this);
        staffsDao = new StaffsDao(staffsDaoConfig, this);
        staffRoleDao = new StaffRoleDao(staffRoleDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);
        sessionEnddayDetailDao = new SessionEnddayDetailDao(sessionEnddayDetailDaoConfig, this);
        saleModeDao = new SaleModeDao(saleModeDaoConfig, this);

        registerDao(BankName.class, bankNameDao);
        registerDao(ComputerName.class, computerNameDao);
        registerDao(CreditCardType.class, creditCardTypeDao);
        registerDao(Document.class, documentDao);
        registerDao(Documenttype.class, documenttypeDao);
        registerDao(FcCardHistory.class, fcCardHistoryDao);
        registerDao(FcCardInfo.class, fcCardInfoDao);
        registerDao(FcTranDetail.class, fcTranDetailDao);
        registerDao(FcTranPayment.class, fcTranPaymentDao);
        registerDao(FcTransaction.class, fcTransactionDao);
        registerDao(Language.class, languageDao);
        registerDao(LogAccessInfo.class, logAccessInfoDao);
        registerDao(OrderDetail.class, orderDetailDao);
        registerDao(OrderpayDetail.class, orderpayDetailDao);
        registerDao(OrderPrintJob.class, orderPrintJobDao);
        registerDao(OrderTransaction.class, orderTransactionDao);
        registerDao(Products.class, productsDao);
        registerDao(ProductDept.class, productDeptDao);
        registerDao(ProductGroup.class, productGroupDao);
        registerDao(ProductCategory.class, productCategoryDao);
        registerDao(ProductComponent.class, productComponentDao);
        registerDao(ProductComponentGroup.class, productComponentGroupDao);
        registerDao(ProductPrice.class, productPriceDao);
        registerDao(ProductPriceGroup.class, productPriceGroupDao);
        registerDao(ProductPriceGroupData.class, productPriceGroupDataDao);
        registerDao(ProductPriceGroupDate.class, productPriceGroupDateDao);
        registerDao(ProductPriceGroupShop.class, productPriceGroupShopDao);
        registerDao(ProductType.class, productTypeDao);
        registerDao(ProductVat.class, productVatDao);
        registerDao(ProgramProperty.class, programPropertyDao);
        registerDao(ProgramPropertyValue.class, programPropertyValueDao);
        registerDao(ShopCategory.class, shopCategoryDao);
        registerDao(ShopData.class, shopDataDao);
        registerDao(Staffs.class, staffsDao);
        registerDao(StaffRole.class, staffRoleDao);
        registerDao(Session.class, sessionDao);
        registerDao(SessionEnddayDetail.class, sessionEnddayDetailDao);
        registerDao(SaleMode.class, saleModeDao);
    }
    
    public void clear() {
        bankNameDaoConfig.getIdentityScope().clear();
        computerNameDaoConfig.getIdentityScope().clear();
        creditCardTypeDaoConfig.getIdentityScope().clear();
        documentDaoConfig.getIdentityScope().clear();
        documenttypeDaoConfig.getIdentityScope().clear();
        fcCardHistoryDaoConfig.getIdentityScope().clear();
        fcCardInfoDaoConfig.getIdentityScope().clear();
        fcTranDetailDaoConfig.getIdentityScope().clear();
        fcTranPaymentDaoConfig.getIdentityScope().clear();
        fcTransactionDaoConfig.getIdentityScope().clear();
        languageDaoConfig.getIdentityScope().clear();
        logAccessInfoDaoConfig.getIdentityScope().clear();
        orderDetailDaoConfig.getIdentityScope().clear();
        orderpayDetailDaoConfig.getIdentityScope().clear();
        orderPrintJobDaoConfig.getIdentityScope().clear();
        orderTransactionDaoConfig.getIdentityScope().clear();
        productsDaoConfig.getIdentityScope().clear();
        productDeptDaoConfig.getIdentityScope().clear();
        productGroupDaoConfig.getIdentityScope().clear();
        productCategoryDaoConfig.getIdentityScope().clear();
        productComponentDaoConfig.getIdentityScope().clear();
        productComponentGroupDaoConfig.getIdentityScope().clear();
        productPriceDaoConfig.getIdentityScope().clear();
        productPriceGroupDaoConfig.getIdentityScope().clear();
        productPriceGroupDataDaoConfig.getIdentityScope().clear();
        productPriceGroupDateDaoConfig.getIdentityScope().clear();
        productPriceGroupShopDaoConfig.getIdentityScope().clear();
        productTypeDaoConfig.getIdentityScope().clear();
        productVatDaoConfig.getIdentityScope().clear();
        programPropertyDaoConfig.getIdentityScope().clear();
        programPropertyValueDaoConfig.getIdentityScope().clear();
        shopCategoryDaoConfig.getIdentityScope().clear();
        shopDataDaoConfig.getIdentityScope().clear();
        staffsDaoConfig.getIdentityScope().clear();
        staffRoleDaoConfig.getIdentityScope().clear();
        sessionDaoConfig.getIdentityScope().clear();
        sessionEnddayDetailDaoConfig.getIdentityScope().clear();
        saleModeDaoConfig.getIdentityScope().clear();
    }

    public BankNameDao getBankNameDao() {
        return bankNameDao;
    }

    public ComputerNameDao getComputerNameDao() {
        return computerNameDao;
    }

    public CreditCardTypeDao getCreditCardTypeDao() {
        return creditCardTypeDao;
    }

    public DocumentDao getDocumentDao() {
        return documentDao;
    }

    public DocumenttypeDao getDocumenttypeDao() {
        return documenttypeDao;
    }

    public FcCardHistoryDao getFcCardHistoryDao() {
        return fcCardHistoryDao;
    }

    public FcCardInfoDao getFcCardInfoDao() {
        return fcCardInfoDao;
    }

    public FcTranDetailDao getFcTranDetailDao() {
        return fcTranDetailDao;
    }

    public FcTranPaymentDao getFcTranPaymentDao() {
        return fcTranPaymentDao;
    }

    public FcTransactionDao getFcTransactionDao() {
        return fcTransactionDao;
    }

    public LanguageDao getLanguageDao() {
        return languageDao;
    }

    public LogAccessInfoDao getLogAccessInfoDao() {
        return logAccessInfoDao;
    }

    public OrderDetailDao getOrderDetailDao() {
        return orderDetailDao;
    }

    public OrderpayDetailDao getOrderpayDetailDao() {
        return orderpayDetailDao;
    }

    public OrderPrintJobDao getOrderPrintJobDao() {
        return orderPrintJobDao;
    }

    public OrderTransactionDao getOrderTransactionDao() {
        return orderTransactionDao;
    }

    public ProductsDao getProductsDao() {
        return productsDao;
    }

    public ProductDeptDao getProductDeptDao() {
        return productDeptDao;
    }

    public ProductGroupDao getProductGroupDao() {
        return productGroupDao;
    }

    public ProductCategoryDao getProductCategoryDao() {
        return productCategoryDao;
    }

    public ProductComponentDao getProductComponentDao() {
        return productComponentDao;
    }

    public ProductComponentGroupDao getProductComponentGroupDao() {
        return productComponentGroupDao;
    }

    public ProductPriceDao getProductPriceDao() {
        return productPriceDao;
    }

    public ProductPriceGroupDao getProductPriceGroupDao() {
        return productPriceGroupDao;
    }

    public ProductPriceGroupDataDao getProductPriceGroupDataDao() {
        return productPriceGroupDataDao;
    }

    public ProductPriceGroupDateDao getProductPriceGroupDateDao() {
        return productPriceGroupDateDao;
    }

    public ProductPriceGroupShopDao getProductPriceGroupShopDao() {
        return productPriceGroupShopDao;
    }

    public ProductTypeDao getProductTypeDao() {
        return productTypeDao;
    }

    public ProductVatDao getProductVatDao() {
        return productVatDao;
    }

    public ProgramPropertyDao getProgramPropertyDao() {
        return programPropertyDao;
    }

    public ProgramPropertyValueDao getProgramPropertyValueDao() {
        return programPropertyValueDao;
    }

    public ShopCategoryDao getShopCategoryDao() {
        return shopCategoryDao;
    }

    public ShopDataDao getShopDataDao() {
        return shopDataDao;
    }

    public StaffsDao getStaffsDao() {
        return staffsDao;
    }

    public StaffRoleDao getStaffRoleDao() {
        return staffRoleDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public SessionEnddayDetailDao getSessionEnddayDetailDao() {
        return sessionEnddayDetailDao;
    }

    public SaleModeDao getSaleModeDao() {
        return saleModeDao;
    }

}
