package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Document.
 */
public class Document {

    private Integer DocumentID;
    private Integer ShopID;
    private Integer VendorID;
    private Integer VendorGroupID;
    private Integer VendorShopID;
    private Integer DocumentTypeID;
    private Integer DocumentYear;
    private Integer DocumentMonth;
    private Integer DocumentNumber;
    private String DocumentDate;
    private Integer InputBy;
    private Integer UpdateBy;
    private Integer ApproveBy;
    private Integer VoidBy;
    private Integer ReceiveBy;
    private Integer DocumentStatus;
    private Integer InvoiceRef;
    private String DocumentUDDID;
    private Integer DocumentIDRef;
    private Integer DocIDRefShopID;
    private Integer InventoryID;
    private Integer ToInvID;
    private Integer FromInvID;
    private Integer FromTemplateID;
    private Integer FromTemplateShopID;
    private Integer IsSmallUnit;
    private String Remark;
    private Integer TermOfPayment;
    private String DueDate;
    private String DocumentHeader;
    private Integer CreditDay;
    private String InsertDate;
    private String UpdateDate;
    private String ApproveDate;
    private String CancelDate;
    private Integer NewSend;
    private Integer CurrentAccessStaff;
    private Double OtherPercentDiscount;
    private Double OtherAmountDiscount;
    private Integer DocumentVATType;
    private Double VATPercent;
    private Integer LockEditDetail;
    private Integer DocumentBatchID;
    private Integer DocumentBatchShopID;
    private Integer AlreadyExportToHQ;
    private Integer AlreadyExportToBranch;
    private Integer IsUpdateDocDetail;

    public Document() {
    }

    public Document(Integer DocumentID) {
        this.DocumentID = DocumentID;
    }

    public Document(Integer DocumentID, Integer ShopID, Integer VendorID, Integer VendorGroupID, Integer VendorShopID, Integer DocumentTypeID, Integer DocumentYear, Integer DocumentMonth, Integer DocumentNumber, String DocumentDate, Integer InputBy, Integer UpdateBy, Integer ApproveBy, Integer VoidBy, Integer ReceiveBy, Integer DocumentStatus, Integer InvoiceRef, String DocumentUDDID, Integer DocumentIDRef, Integer DocIDRefShopID, Integer InventoryID, Integer ToInvID, Integer FromInvID, Integer FromTemplateID, Integer FromTemplateShopID, Integer IsSmallUnit, String Remark, Integer TermOfPayment, String DueDate, String DocumentHeader, Integer CreditDay, String InsertDate, String UpdateDate, String ApproveDate, String CancelDate, Integer NewSend, Integer CurrentAccessStaff, Double OtherPercentDiscount, Double OtherAmountDiscount, Integer DocumentVATType, Double VATPercent, Integer LockEditDetail, Integer DocumentBatchID, Integer DocumentBatchShopID, Integer AlreadyExportToHQ, Integer AlreadyExportToBranch, Integer IsUpdateDocDetail) {
        this.DocumentID = DocumentID;
        this.ShopID = ShopID;
        this.VendorID = VendorID;
        this.VendorGroupID = VendorGroupID;
        this.VendorShopID = VendorShopID;
        this.DocumentTypeID = DocumentTypeID;
        this.DocumentYear = DocumentYear;
        this.DocumentMonth = DocumentMonth;
        this.DocumentNumber = DocumentNumber;
        this.DocumentDate = DocumentDate;
        this.InputBy = InputBy;
        this.UpdateBy = UpdateBy;
        this.ApproveBy = ApproveBy;
        this.VoidBy = VoidBy;
        this.ReceiveBy = ReceiveBy;
        this.DocumentStatus = DocumentStatus;
        this.InvoiceRef = InvoiceRef;
        this.DocumentUDDID = DocumentUDDID;
        this.DocumentIDRef = DocumentIDRef;
        this.DocIDRefShopID = DocIDRefShopID;
        this.InventoryID = InventoryID;
        this.ToInvID = ToInvID;
        this.FromInvID = FromInvID;
        this.FromTemplateID = FromTemplateID;
        this.FromTemplateShopID = FromTemplateShopID;
        this.IsSmallUnit = IsSmallUnit;
        this.Remark = Remark;
        this.TermOfPayment = TermOfPayment;
        this.DueDate = DueDate;
        this.DocumentHeader = DocumentHeader;
        this.CreditDay = CreditDay;
        this.InsertDate = InsertDate;
        this.UpdateDate = UpdateDate;
        this.ApproveDate = ApproveDate;
        this.CancelDate = CancelDate;
        this.NewSend = NewSend;
        this.CurrentAccessStaff = CurrentAccessStaff;
        this.OtherPercentDiscount = OtherPercentDiscount;
        this.OtherAmountDiscount = OtherAmountDiscount;
        this.DocumentVATType = DocumentVATType;
        this.VATPercent = VATPercent;
        this.LockEditDetail = LockEditDetail;
        this.DocumentBatchID = DocumentBatchID;
        this.DocumentBatchShopID = DocumentBatchShopID;
        this.AlreadyExportToHQ = AlreadyExportToHQ;
        this.AlreadyExportToBranch = AlreadyExportToBranch;
        this.IsUpdateDocDetail = IsUpdateDocDetail;
    }

    public Integer getDocumentID() {
        return DocumentID;
    }

    public void setDocumentID(Integer DocumentID) {
        this.DocumentID = DocumentID;
    }

    public Integer getShopID() {
        return ShopID;
    }

    public void setShopID(Integer ShopID) {
        this.ShopID = ShopID;
    }

    public Integer getVendorID() {
        return VendorID;
    }

    public void setVendorID(Integer VendorID) {
        this.VendorID = VendorID;
    }

    public Integer getVendorGroupID() {
        return VendorGroupID;
    }

    public void setVendorGroupID(Integer VendorGroupID) {
        this.VendorGroupID = VendorGroupID;
    }

    public Integer getVendorShopID() {
        return VendorShopID;
    }

    public void setVendorShopID(Integer VendorShopID) {
        this.VendorShopID = VendorShopID;
    }

    public Integer getDocumentTypeID() {
        return DocumentTypeID;
    }

    public void setDocumentTypeID(Integer DocumentTypeID) {
        this.DocumentTypeID = DocumentTypeID;
    }

    public Integer getDocumentYear() {
        return DocumentYear;
    }

    public void setDocumentYear(Integer DocumentYear) {
        this.DocumentYear = DocumentYear;
    }

    public Integer getDocumentMonth() {
        return DocumentMonth;
    }

    public void setDocumentMonth(Integer DocumentMonth) {
        this.DocumentMonth = DocumentMonth;
    }

    public Integer getDocumentNumber() {
        return DocumentNumber;
    }

    public void setDocumentNumber(Integer DocumentNumber) {
        this.DocumentNumber = DocumentNumber;
    }

    public String getDocumentDate() {
        return DocumentDate;
    }

    public void setDocumentDate(String DocumentDate) {
        this.DocumentDate = DocumentDate;
    }

    public Integer getInputBy() {
        return InputBy;
    }

    public void setInputBy(Integer InputBy) {
        this.InputBy = InputBy;
    }

    public Integer getUpdateBy() {
        return UpdateBy;
    }

    public void setUpdateBy(Integer UpdateBy) {
        this.UpdateBy = UpdateBy;
    }

    public Integer getApproveBy() {
        return ApproveBy;
    }

    public void setApproveBy(Integer ApproveBy) {
        this.ApproveBy = ApproveBy;
    }

    public Integer getVoidBy() {
        return VoidBy;
    }

    public void setVoidBy(Integer VoidBy) {
        this.VoidBy = VoidBy;
    }

    public Integer getReceiveBy() {
        return ReceiveBy;
    }

    public void setReceiveBy(Integer ReceiveBy) {
        this.ReceiveBy = ReceiveBy;
    }

    public Integer getDocumentStatus() {
        return DocumentStatus;
    }

    public void setDocumentStatus(Integer DocumentStatus) {
        this.DocumentStatus = DocumentStatus;
    }

    public Integer getInvoiceRef() {
        return InvoiceRef;
    }

    public void setInvoiceRef(Integer InvoiceRef) {
        this.InvoiceRef = InvoiceRef;
    }

    public String getDocumentUDDID() {
        return DocumentUDDID;
    }

    public void setDocumentUDDID(String DocumentUDDID) {
        this.DocumentUDDID = DocumentUDDID;
    }

    public Integer getDocumentIDRef() {
        return DocumentIDRef;
    }

    public void setDocumentIDRef(Integer DocumentIDRef) {
        this.DocumentIDRef = DocumentIDRef;
    }

    public Integer getDocIDRefShopID() {
        return DocIDRefShopID;
    }

    public void setDocIDRefShopID(Integer DocIDRefShopID) {
        this.DocIDRefShopID = DocIDRefShopID;
    }

    public Integer getInventoryID() {
        return InventoryID;
    }

    public void setInventoryID(Integer InventoryID) {
        this.InventoryID = InventoryID;
    }

    public Integer getToInvID() {
        return ToInvID;
    }

    public void setToInvID(Integer ToInvID) {
        this.ToInvID = ToInvID;
    }

    public Integer getFromInvID() {
        return FromInvID;
    }

    public void setFromInvID(Integer FromInvID) {
        this.FromInvID = FromInvID;
    }

    public Integer getFromTemplateID() {
        return FromTemplateID;
    }

    public void setFromTemplateID(Integer FromTemplateID) {
        this.FromTemplateID = FromTemplateID;
    }

    public Integer getFromTemplateShopID() {
        return FromTemplateShopID;
    }

    public void setFromTemplateShopID(Integer FromTemplateShopID) {
        this.FromTemplateShopID = FromTemplateShopID;
    }

    public Integer getIsSmallUnit() {
        return IsSmallUnit;
    }

    public void setIsSmallUnit(Integer IsSmallUnit) {
        this.IsSmallUnit = IsSmallUnit;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public Integer getTermOfPayment() {
        return TermOfPayment;
    }

    public void setTermOfPayment(Integer TermOfPayment) {
        this.TermOfPayment = TermOfPayment;
    }

    public String getDueDate() {
        return DueDate;
    }

    public void setDueDate(String DueDate) {
        this.DueDate = DueDate;
    }

    public String getDocumentHeader() {
        return DocumentHeader;
    }

    public void setDocumentHeader(String DocumentHeader) {
        this.DocumentHeader = DocumentHeader;
    }

    public Integer getCreditDay() {
        return CreditDay;
    }

    public void setCreditDay(Integer CreditDay) {
        this.CreditDay = CreditDay;
    }

    public String getInsertDate() {
        return InsertDate;
    }

    public void setInsertDate(String InsertDate) {
        this.InsertDate = InsertDate;
    }

    public String getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(String UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

    public String getApproveDate() {
        return ApproveDate;
    }

    public void setApproveDate(String ApproveDate) {
        this.ApproveDate = ApproveDate;
    }

    public String getCancelDate() {
        return CancelDate;
    }

    public void setCancelDate(String CancelDate) {
        this.CancelDate = CancelDate;
    }

    public Integer getNewSend() {
        return NewSend;
    }

    public void setNewSend(Integer NewSend) {
        this.NewSend = NewSend;
    }

    public Integer getCurrentAccessStaff() {
        return CurrentAccessStaff;
    }

    public void setCurrentAccessStaff(Integer CurrentAccessStaff) {
        this.CurrentAccessStaff = CurrentAccessStaff;
    }

    public Double getOtherPercentDiscount() {
        return OtherPercentDiscount;
    }

    public void setOtherPercentDiscount(Double OtherPercentDiscount) {
        this.OtherPercentDiscount = OtherPercentDiscount;
    }

    public Double getOtherAmountDiscount() {
        return OtherAmountDiscount;
    }

    public void setOtherAmountDiscount(Double OtherAmountDiscount) {
        this.OtherAmountDiscount = OtherAmountDiscount;
    }

    public Integer getDocumentVATType() {
        return DocumentVATType;
    }

    public void setDocumentVATType(Integer DocumentVATType) {
        this.DocumentVATType = DocumentVATType;
    }

    public Double getVATPercent() {
        return VATPercent;
    }

    public void setVATPercent(Double VATPercent) {
        this.VATPercent = VATPercent;
    }

    public Integer getLockEditDetail() {
        return LockEditDetail;
    }

    public void setLockEditDetail(Integer LockEditDetail) {
        this.LockEditDetail = LockEditDetail;
    }

    public Integer getDocumentBatchID() {
        return DocumentBatchID;
    }

    public void setDocumentBatchID(Integer DocumentBatchID) {
        this.DocumentBatchID = DocumentBatchID;
    }

    public Integer getDocumentBatchShopID() {
        return DocumentBatchShopID;
    }

    public void setDocumentBatchShopID(Integer DocumentBatchShopID) {
        this.DocumentBatchShopID = DocumentBatchShopID;
    }

    public Integer getAlreadyExportToHQ() {
        return AlreadyExportToHQ;
    }

    public void setAlreadyExportToHQ(Integer AlreadyExportToHQ) {
        this.AlreadyExportToHQ = AlreadyExportToHQ;
    }

    public Integer getAlreadyExportToBranch() {
        return AlreadyExportToBranch;
    }

    public void setAlreadyExportToBranch(Integer AlreadyExportToBranch) {
        this.AlreadyExportToBranch = AlreadyExportToBranch;
    }

    public Integer getIsUpdateDocDetail() {
        return IsUpdateDocDetail;
    }

    public void setIsUpdateDocDetail(Integer IsUpdateDocDetail) {
        this.IsUpdateDocDetail = IsUpdateDocDetail;
    }

}
