package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table fc_cardhistory.
 */
public class FcCardHistory {

    private Integer HistoryID;
    private Integer TranUUID;
    private Integer CardID;
    private String CardNo;
    private Integer TransactionID;
    private Integer ComputerID;
    private Integer ShopID;
    private java.util.Date SaleDate;
    private String ReceiptNo;
    private Double PreviousBalance;
    private Double TranAmount;
    private Integer DocType;
    private Integer StaffID;
    private java.util.Date InsertDate;

    public FcCardHistory() {
    }

    public FcCardHistory(Integer HistoryID) {
        this.HistoryID = HistoryID;
    }

    public FcCardHistory(Integer HistoryID, Integer TranUUID, Integer CardID, String CardNo, Integer TransactionID, Integer ComputerID, Integer ShopID, java.util.Date SaleDate, String ReceiptNo, Double PreviousBalance, Double TranAmount, Integer DocType, Integer StaffID, java.util.Date InsertDate) {
        this.HistoryID = HistoryID;
        this.TranUUID = TranUUID;
        this.CardID = CardID;
        this.CardNo = CardNo;
        this.TransactionID = TransactionID;
        this.ComputerID = ComputerID;
        this.ShopID = ShopID;
        this.SaleDate = SaleDate;
        this.ReceiptNo = ReceiptNo;
        this.PreviousBalance = PreviousBalance;
        this.TranAmount = TranAmount;
        this.DocType = DocType;
        this.StaffID = StaffID;
        this.InsertDate = InsertDate;
    }

    public Integer getHistoryID() {
        return HistoryID;
    }

    public void setHistoryID(Integer HistoryID) {
        this.HistoryID = HistoryID;
    }

    public Integer getTranUUID() {
        return TranUUID;
    }

    public void setTranUUID(Integer TranUUID) {
        this.TranUUID = TranUUID;
    }

    public Integer getCardID() {
        return CardID;
    }

    public void setCardID(Integer CardID) {
        this.CardID = CardID;
    }

    public String getCardNo() {
        return CardNo;
    }

    public void setCardNo(String CardNo) {
        this.CardNo = CardNo;
    }

    public Integer getTransactionID() {
        return TransactionID;
    }

    public void setTransactionID(Integer TransactionID) {
        this.TransactionID = TransactionID;
    }

    public Integer getComputerID() {
        return ComputerID;
    }

    public void setComputerID(Integer ComputerID) {
        this.ComputerID = ComputerID;
    }

    public Integer getShopID() {
        return ShopID;
    }

    public void setShopID(Integer ShopID) {
        this.ShopID = ShopID;
    }

    public java.util.Date getSaleDate() {
        return SaleDate;
    }

    public void setSaleDate(java.util.Date SaleDate) {
        this.SaleDate = SaleDate;
    }

    public String getReceiptNo() {
        return ReceiptNo;
    }

    public void setReceiptNo(String ReceiptNo) {
        this.ReceiptNo = ReceiptNo;
    }

    public Double getPreviousBalance() {
        return PreviousBalance;
    }

    public void setPreviousBalance(Double PreviousBalance) {
        this.PreviousBalance = PreviousBalance;
    }

    public Double getTranAmount() {
        return TranAmount;
    }

    public void setTranAmount(Double TranAmount) {
        this.TranAmount = TranAmount;
    }

    public Integer getDocType() {
        return DocType;
    }

    public void setDocType(Integer DocType) {
        this.DocType = DocType;
    }

    public Integer getStaffID() {
        return StaffID;
    }

    public void setStaffID(Integer StaffID) {
        this.StaffID = StaffID;
    }

    public java.util.Date getInsertDate() {
        return InsertDate;
    }

    public void setInsertDate(java.util.Date InsertDate) {
        this.InsertDate = InsertDate;
    }

}
