package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LogAccessInfo.
 */
public class LogAccessInfo {

    private Integer AccessID;
    private String AccessName;
    private Integer Deleted;

    public LogAccessInfo() {
    }

    public LogAccessInfo(Integer AccessID) {
        this.AccessID = AccessID;
    }

    public LogAccessInfo(Integer AccessID, String AccessName, Integer Deleted) {
        this.AccessID = AccessID;
        this.AccessName = AccessName;
        this.Deleted = Deleted;
    }

    public Integer getAccessID() {
        return AccessID;
    }

    public void setAccessID(Integer AccessID) {
        this.AccessID = AccessID;
    }

    public String getAccessName() {
        return AccessName;
    }

    public void setAccessName(String AccessName) {
        this.AccessName = AccessName;
    }

    public Integer getDeleted() {
        return Deleted;
    }

    public void setDeleted(Integer Deleted) {
        this.Deleted = Deleted;
    }

}
