package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OrderPrintJob.
 */
public class OrderPrintJob {

    private Integer TransactionID;
    private Integer ComputerID;
    private Integer OrderDetailID;
    private Integer PrintNo;
    private Integer PrinterID;
    private Integer IsPrintSummary;
    private String InsertDateTime;
    private String PrintDateTime;
    private String FinishDateTime;
    private String SaleDate;
    private Integer ShopID;
    private Integer PrintFromComputerID;
    private Integer PrintStatus;

    public OrderPrintJob() {
    }

    public OrderPrintJob(Integer TransactionID, Integer ComputerID, Integer OrderDetailID, Integer PrintNo) {
        this.TransactionID = TransactionID;
        this.ComputerID = ComputerID;
        this.OrderDetailID = OrderDetailID;
        this.PrintNo = PrintNo;
    }

    public OrderPrintJob(Integer TransactionID, Integer ComputerID, Integer OrderDetailID, Integer PrintNo, Integer PrinterID, Integer IsPrintSummary, String InsertDateTime, String PrintDateTime, String FinishDateTime, String SaleDate, Integer ShopID, Integer PrintFromComputerID, Integer PrintStatus) {
        this.TransactionID = TransactionID;
        this.ComputerID = ComputerID;
        this.OrderDetailID = OrderDetailID;
        this.PrintNo = PrintNo;
        this.PrinterID = PrinterID;
        this.IsPrintSummary = IsPrintSummary;
        this.InsertDateTime = InsertDateTime;
        this.PrintDateTime = PrintDateTime;
        this.FinishDateTime = FinishDateTime;
        this.SaleDate = SaleDate;
        this.ShopID = ShopID;
        this.PrintFromComputerID = PrintFromComputerID;
        this.PrintStatus = PrintStatus;
    }

    public Integer getTransactionID() {
        return TransactionID;
    }

    public void setTransactionID(Integer TransactionID) {
        this.TransactionID = TransactionID;
    }

    public Integer getComputerID() {
        return ComputerID;
    }

    public void setComputerID(Integer ComputerID) {
        this.ComputerID = ComputerID;
    }

    public Integer getOrderDetailID() {
        return OrderDetailID;
    }

    public void setOrderDetailID(Integer OrderDetailID) {
        this.OrderDetailID = OrderDetailID;
    }

    public Integer getPrintNo() {
        return PrintNo;
    }

    public void setPrintNo(Integer PrintNo) {
        this.PrintNo = PrintNo;
    }

    public Integer getPrinterID() {
        return PrinterID;
    }

    public void setPrinterID(Integer PrinterID) {
        this.PrinterID = PrinterID;
    }

    public Integer getIsPrintSummary() {
        return IsPrintSummary;
    }

    public void setIsPrintSummary(Integer IsPrintSummary) {
        this.IsPrintSummary = IsPrintSummary;
    }

    public String getInsertDateTime() {
        return InsertDateTime;
    }

    public void setInsertDateTime(String InsertDateTime) {
        this.InsertDateTime = InsertDateTime;
    }

    public String getPrintDateTime() {
        return PrintDateTime;
    }

    public void setPrintDateTime(String PrintDateTime) {
        this.PrintDateTime = PrintDateTime;
    }

    public String getFinishDateTime() {
        return FinishDateTime;
    }

    public void setFinishDateTime(String FinishDateTime) {
        this.FinishDateTime = FinishDateTime;
    }

    public String getSaleDate() {
        return SaleDate;
    }

    public void setSaleDate(String SaleDate) {
        this.SaleDate = SaleDate;
    }

    public Integer getShopID() {
        return ShopID;
    }

    public void setShopID(Integer ShopID) {
        this.ShopID = ShopID;
    }

    public Integer getPrintFromComputerID() {
        return PrintFromComputerID;
    }

    public void setPrintFromComputerID(Integer PrintFromComputerID) {
        this.PrintFromComputerID = PrintFromComputerID;
    }

    public Integer getPrintStatus() {
        return PrintStatus;
    }

    public void setPrintStatus(Integer PrintStatus) {
        this.PrintStatus = PrintStatus;
    }

}
