package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORDER_DETAILFRONT.
 */
public class OrderDetailfront {


    public OrderDetailfront() {
    }

    public OrderDetailfront() {
    }

}
