package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORDER_TRANSACTION.
 */
public class OrderTransaction {

    private int TransactionID;
    private int ComputerID;
    /** Not-null value. */
    private String TransactionUUID;
    private java.util.Date ReserveTime;
    private Integer ReserveStaffID;
    /** Not-null value. */
    private java.util.Date OpenTime;
    private int OpenStaffID;
    private java.util.Date PaidTime;
    private Integer PaidStaffID;
    private java.util.Date CloseTime;
    private Integer CommStaffID;
    private Double OtherPercentDiscount;
    private Double OtherAmountDiscount;
    private int TransactionStatusID;
    private int SaleMode;
    private String TransactionName;
    private String QueueName;
    private Integer NoCustomer;
    private Integer NoCustomerWhenOpen;
    private int DocType;
    private int ReceiptYear;
    private int ReceiptMonth;
    private Integer ReceiptID;
    private String ReceiptNumber;
    /** Not-null value. */
    private java.util.Date SaleDate;
    private int ShopID;
    private Double TransactionVAT;
    private Double TransactionExcludeVAT;
    private Double ServiceCharge;
    private Double ServiceChargeVAT;
    private Double OtherIncome;
    private Double OtherIncomeVAT;
    private Double TransactionVATable;
    private Double ReceiptProductRetailPrice;
    private Double ReceiptSalePrice;
    private Double ReceiptPayPrice;
    private Double ReceiptDiscount;
    private Double ReceiptTotalQty;
    private Double VATPercent;
    private Double ServiceChargePercent;
    private Integer IsCalculateServiceCharge;
    private int SessionID;
    private Integer CloseComputerID;
    private Integer VoidStaffID;
    private String VoidReason;
    private java.util.Date VoidTime;
    private Integer MemberID;
    private Integer HasOrder;
    private Integer NoPrintBillDetail;
    private Integer BillDetailReferenceNo;
    private Integer CallForCheckBill;
    private String TransactionNote;
    private Integer CurrentAccessComputer;
    private java.util.Date UpdateDate;
    private java.util.Date BeginTime;
    private java.util.Date EndTime;
    private java.util.Date PrintWarningTime;
    private Integer PrintBeginTime;
    private Integer AlreadyCalculateStock;
    private Integer AlreadyExportToHQ;
    private Integer TableID;
    private Integer IsSplitTransaction;
    private Integer IsFromOtherTransaction;
    private String ReferenceNo;
    private Integer FromDepositTransactionID;
    private Integer FromDepositComputerID;
    private Integer Deleted;

    public OrderTransaction() {
    }

    public OrderTransaction(int TransactionID) {
        this.TransactionID = TransactionID;
    }

    public OrderTransaction(int TransactionID, int ComputerID, String TransactionUUID, java.util.Date ReserveTime, Integer ReserveStaffID, java.util.Date OpenTime, int OpenStaffID, java.util.Date PaidTime, Integer PaidStaffID, java.util.Date CloseTime, Integer CommStaffID, Double OtherPercentDiscount, Double OtherAmountDiscount, int TransactionStatusID, int SaleMode, String TransactionName, String QueueName, Integer NoCustomer, Integer NoCustomerWhenOpen, int DocType, int ReceiptYear, int ReceiptMonth, Integer ReceiptID, String ReceiptNumber, java.util.Date SaleDate, int ShopID, Double TransactionVAT, Double TransactionExcludeVAT, Double ServiceCharge, Double ServiceChargeVAT, Double OtherIncome, Double OtherIncomeVAT, Double TransactionVATable, Double ReceiptProductRetailPrice, Double ReceiptSalePrice, Double ReceiptPayPrice, Double ReceiptDiscount, Double ReceiptTotalQty, Double VATPercent, Double ServiceChargePercent, Integer IsCalculateServiceCharge, int SessionID, Integer CloseComputerID, Integer VoidStaffID, String VoidReason, java.util.Date VoidTime, Integer MemberID, Integer HasOrder, Integer NoPrintBillDetail, Integer BillDetailReferenceNo, Integer CallForCheckBill, String TransactionNote, Integer CurrentAccessComputer, java.util.Date UpdateDate, java.util.Date BeginTime, java.util.Date EndTime, java.util.Date PrintWarningTime, Integer PrintBeginTime, Integer AlreadyCalculateStock, Integer AlreadyExportToHQ, Integer TableID, Integer IsSplitTransaction, Integer IsFromOtherTransaction, String ReferenceNo, Integer FromDepositTransactionID, Integer FromDepositComputerID, Integer Deleted) {
        this.TransactionID = TransactionID;
        this.ComputerID = ComputerID;
        this.TransactionUUID = TransactionUUID;
        this.ReserveTime = ReserveTime;
        this.ReserveStaffID = ReserveStaffID;
        this.OpenTime = OpenTime;
        this.OpenStaffID = OpenStaffID;
        this.PaidTime = PaidTime;
        this.PaidStaffID = PaidStaffID;
        this.CloseTime = CloseTime;
        this.CommStaffID = CommStaffID;
        this.OtherPercentDiscount = OtherPercentDiscount;
        this.OtherAmountDiscount = OtherAmountDiscount;
        this.TransactionStatusID = TransactionStatusID;
        this.SaleMode = SaleMode;
        this.TransactionName = TransactionName;
        this.QueueName = QueueName;
        this.NoCustomer = NoCustomer;
        this.NoCustomerWhenOpen = NoCustomerWhenOpen;
        this.DocType = DocType;
        this.ReceiptYear = ReceiptYear;
        this.ReceiptMonth = ReceiptMonth;
        this.ReceiptID = ReceiptID;
        this.ReceiptNumber = ReceiptNumber;
        this.SaleDate = SaleDate;
        this.ShopID = ShopID;
        this.TransactionVAT = TransactionVAT;
        this.TransactionExcludeVAT = TransactionExcludeVAT;
        this.ServiceCharge = ServiceCharge;
        this.ServiceChargeVAT = ServiceChargeVAT;
        this.OtherIncome = OtherIncome;
        this.OtherIncomeVAT = OtherIncomeVAT;
        this.TransactionVATable = TransactionVATable;
        this.ReceiptProductRetailPrice = ReceiptProductRetailPrice;
        this.ReceiptSalePrice = ReceiptSalePrice;
        this.ReceiptPayPrice = ReceiptPayPrice;
        this.ReceiptDiscount = ReceiptDiscount;
        this.ReceiptTotalQty = ReceiptTotalQty;
        this.VATPercent = VATPercent;
        this.ServiceChargePercent = ServiceChargePercent;
        this.IsCalculateServiceCharge = IsCalculateServiceCharge;
        this.SessionID = SessionID;
        this.CloseComputerID = CloseComputerID;
        this.VoidStaffID = VoidStaffID;
        this.VoidReason = VoidReason;
        this.VoidTime = VoidTime;
        this.MemberID = MemberID;
        this.HasOrder = HasOrder;
        this.NoPrintBillDetail = NoPrintBillDetail;
        this.BillDetailReferenceNo = BillDetailReferenceNo;
        this.CallForCheckBill = CallForCheckBill;
        this.TransactionNote = TransactionNote;
        this.CurrentAccessComputer = CurrentAccessComputer;
        this.UpdateDate = UpdateDate;
        this.BeginTime = BeginTime;
        this.EndTime = EndTime;
        this.PrintWarningTime = PrintWarningTime;
        this.PrintBeginTime = PrintBeginTime;
        this.AlreadyCalculateStock = AlreadyCalculateStock;
        this.AlreadyExportToHQ = AlreadyExportToHQ;
        this.TableID = TableID;
        this.IsSplitTransaction = IsSplitTransaction;
        this.IsFromOtherTransaction = IsFromOtherTransaction;
        this.ReferenceNo = ReferenceNo;
        this.FromDepositTransactionID = FromDepositTransactionID;
        this.FromDepositComputerID = FromDepositComputerID;
        this.Deleted = Deleted;
    }

    public int getTransactionID() {
        return TransactionID;
    }

    public void setTransactionID(int TransactionID) {
        this.TransactionID = TransactionID;
    }

    public int getComputerID() {
        return ComputerID;
    }

    public void setComputerID(int ComputerID) {
        this.ComputerID = ComputerID;
    }

    /** Not-null value. */
    public String getTransactionUUID() {
        return TransactionUUID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTransactionUUID(String TransactionUUID) {
        this.TransactionUUID = TransactionUUID;
    }

    public java.util.Date getReserveTime() {
        return ReserveTime;
    }

    public void setReserveTime(java.util.Date ReserveTime) {
        this.ReserveTime = ReserveTime;
    }

    public Integer getReserveStaffID() {
        return ReserveStaffID;
    }

    public void setReserveStaffID(Integer ReserveStaffID) {
        this.ReserveStaffID = ReserveStaffID;
    }

    /** Not-null value. */
    public java.util.Date getOpenTime() {
        return OpenTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOpenTime(java.util.Date OpenTime) {
        this.OpenTime = OpenTime;
    }

    public int getOpenStaffID() {
        return OpenStaffID;
    }

    public void setOpenStaffID(int OpenStaffID) {
        this.OpenStaffID = OpenStaffID;
    }

    public java.util.Date getPaidTime() {
        return PaidTime;
    }

    public void setPaidTime(java.util.Date PaidTime) {
        this.PaidTime = PaidTime;
    }

    public Integer getPaidStaffID() {
        return PaidStaffID;
    }

    public void setPaidStaffID(Integer PaidStaffID) {
        this.PaidStaffID = PaidStaffID;
    }

    public java.util.Date getCloseTime() {
        return CloseTime;
    }

    public void setCloseTime(java.util.Date CloseTime) {
        this.CloseTime = CloseTime;
    }

    public Integer getCommStaffID() {
        return CommStaffID;
    }

    public void setCommStaffID(Integer CommStaffID) {
        this.CommStaffID = CommStaffID;
    }

    public Double getOtherPercentDiscount() {
        return OtherPercentDiscount;
    }

    public void setOtherPercentDiscount(Double OtherPercentDiscount) {
        this.OtherPercentDiscount = OtherPercentDiscount;
    }

    public Double getOtherAmountDiscount() {
        return OtherAmountDiscount;
    }

    public void setOtherAmountDiscount(Double OtherAmountDiscount) {
        this.OtherAmountDiscount = OtherAmountDiscount;
    }

    public int getTransactionStatusID() {
        return TransactionStatusID;
    }

    public void setTransactionStatusID(int TransactionStatusID) {
        this.TransactionStatusID = TransactionStatusID;
    }

    public int getSaleMode() {
        return SaleMode;
    }

    public void setSaleMode(int SaleMode) {
        this.SaleMode = SaleMode;
    }

    public String getTransactionName() {
        return TransactionName;
    }

    public void setTransactionName(String TransactionName) {
        this.TransactionName = TransactionName;
    }

    public String getQueueName() {
        return QueueName;
    }

    public void setQueueName(String QueueName) {
        this.QueueName = QueueName;
    }

    public Integer getNoCustomer() {
        return NoCustomer;
    }

    public void setNoCustomer(Integer NoCustomer) {
        this.NoCustomer = NoCustomer;
    }

    public Integer getNoCustomerWhenOpen() {
        return NoCustomerWhenOpen;
    }

    public void setNoCustomerWhenOpen(Integer NoCustomerWhenOpen) {
        this.NoCustomerWhenOpen = NoCustomerWhenOpen;
    }

    public int getDocType() {
        return DocType;
    }

    public void setDocType(int DocType) {
        this.DocType = DocType;
    }

    public int getReceiptYear() {
        return ReceiptYear;
    }

    public void setReceiptYear(int ReceiptYear) {
        this.ReceiptYear = ReceiptYear;
    }

    public int getReceiptMonth() {
        return ReceiptMonth;
    }

    public void setReceiptMonth(int ReceiptMonth) {
        this.ReceiptMonth = ReceiptMonth;
    }

    public Integer getReceiptID() {
        return ReceiptID;
    }

    public void setReceiptID(Integer ReceiptID) {
        this.ReceiptID = ReceiptID;
    }

    public String getReceiptNumber() {
        return ReceiptNumber;
    }

    public void setReceiptNumber(String ReceiptNumber) {
        this.ReceiptNumber = ReceiptNumber;
    }

    /** Not-null value. */
    public java.util.Date getSaleDate() {
        return SaleDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSaleDate(java.util.Date SaleDate) {
        this.SaleDate = SaleDate;
    }

    public int getShopID() {
        return ShopID;
    }

    public void setShopID(int ShopID) {
        this.ShopID = ShopID;
    }

    public Double getTransactionVAT() {
        return TransactionVAT;
    }

    public void setTransactionVAT(Double TransactionVAT) {
        this.TransactionVAT = TransactionVAT;
    }

    public Double getTransactionExcludeVAT() {
        return TransactionExcludeVAT;
    }

    public void setTransactionExcludeVAT(Double TransactionExcludeVAT) {
        this.TransactionExcludeVAT = TransactionExcludeVAT;
    }

    public Double getServiceCharge() {
        return ServiceCharge;
    }

    public void setServiceCharge(Double ServiceCharge) {
        this.ServiceCharge = ServiceCharge;
    }

    public Double getServiceChargeVAT() {
        return ServiceChargeVAT;
    }

    public void setServiceChargeVAT(Double ServiceChargeVAT) {
        this.ServiceChargeVAT = ServiceChargeVAT;
    }

    public Double getOtherIncome() {
        return OtherIncome;
    }

    public void setOtherIncome(Double OtherIncome) {
        this.OtherIncome = OtherIncome;
    }

    public Double getOtherIncomeVAT() {
        return OtherIncomeVAT;
    }

    public void setOtherIncomeVAT(Double OtherIncomeVAT) {
        this.OtherIncomeVAT = OtherIncomeVAT;
    }

    public Double getTransactionVATable() {
        return TransactionVATable;
    }

    public void setTransactionVATable(Double TransactionVATable) {
        this.TransactionVATable = TransactionVATable;
    }

    public Double getReceiptProductRetailPrice() {
        return ReceiptProductRetailPrice;
    }

    public void setReceiptProductRetailPrice(Double ReceiptProductRetailPrice) {
        this.ReceiptProductRetailPrice = ReceiptProductRetailPrice;
    }

    public Double getReceiptSalePrice() {
        return ReceiptSalePrice;
    }

    public void setReceiptSalePrice(Double ReceiptSalePrice) {
        this.ReceiptSalePrice = ReceiptSalePrice;
    }

    public Double getReceiptPayPrice() {
        return ReceiptPayPrice;
    }

    public void setReceiptPayPrice(Double ReceiptPayPrice) {
        this.ReceiptPayPrice = ReceiptPayPrice;
    }

    public Double getReceiptDiscount() {
        return ReceiptDiscount;
    }

    public void setReceiptDiscount(Double ReceiptDiscount) {
        this.ReceiptDiscount = ReceiptDiscount;
    }

    public Double getReceiptTotalQty() {
        return ReceiptTotalQty;
    }

    public void setReceiptTotalQty(Double ReceiptTotalQty) {
        this.ReceiptTotalQty = ReceiptTotalQty;
    }

    public Double getVATPercent() {
        return VATPercent;
    }

    public void setVATPercent(Double VATPercent) {
        this.VATPercent = VATPercent;
    }

    public Double getServiceChargePercent() {
        return ServiceChargePercent;
    }

    public void setServiceChargePercent(Double ServiceChargePercent) {
        this.ServiceChargePercent = ServiceChargePercent;
    }

    public Integer getIsCalculateServiceCharge() {
        return IsCalculateServiceCharge;
    }

    public void setIsCalculateServiceCharge(Integer IsCalculateServiceCharge) {
        this.IsCalculateServiceCharge = IsCalculateServiceCharge;
    }

    public int getSessionID() {
        return SessionID;
    }

    public void setSessionID(int SessionID) {
        this.SessionID = SessionID;
    }

    public Integer getCloseComputerID() {
        return CloseComputerID;
    }

    public void setCloseComputerID(Integer CloseComputerID) {
        this.CloseComputerID = CloseComputerID;
    }

    public Integer getVoidStaffID() {
        return VoidStaffID;
    }

    public void setVoidStaffID(Integer VoidStaffID) {
        this.VoidStaffID = VoidStaffID;
    }

    public String getVoidReason() {
        return VoidReason;
    }

    public void setVoidReason(String VoidReason) {
        this.VoidReason = VoidReason;
    }

    public java.util.Date getVoidTime() {
        return VoidTime;
    }

    public void setVoidTime(java.util.Date VoidTime) {
        this.VoidTime = VoidTime;
    }

    public Integer getMemberID() {
        return MemberID;
    }

    public void setMemberID(Integer MemberID) {
        this.MemberID = MemberID;
    }

    public Integer getHasOrder() {
        return HasOrder;
    }

    public void setHasOrder(Integer HasOrder) {
        this.HasOrder = HasOrder;
    }

    public Integer getNoPrintBillDetail() {
        return NoPrintBillDetail;
    }

    public void setNoPrintBillDetail(Integer NoPrintBillDetail) {
        this.NoPrintBillDetail = NoPrintBillDetail;
    }

    public Integer getBillDetailReferenceNo() {
        return BillDetailReferenceNo;
    }

    public void setBillDetailReferenceNo(Integer BillDetailReferenceNo) {
        this.BillDetailReferenceNo = BillDetailReferenceNo;
    }

    public Integer getCallForCheckBill() {
        return CallForCheckBill;
    }

    public void setCallForCheckBill(Integer CallForCheckBill) {
        this.CallForCheckBill = CallForCheckBill;
    }

    public String getTransactionNote() {
        return TransactionNote;
    }

    public void setTransactionNote(String TransactionNote) {
        this.TransactionNote = TransactionNote;
    }

    public Integer getCurrentAccessComputer() {
        return CurrentAccessComputer;
    }

    public void setCurrentAccessComputer(Integer CurrentAccessComputer) {
        this.CurrentAccessComputer = CurrentAccessComputer;
    }

    public java.util.Date getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(java.util.Date UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

    public java.util.Date getBeginTime() {
        return BeginTime;
    }

    public void setBeginTime(java.util.Date BeginTime) {
        this.BeginTime = BeginTime;
    }

    public java.util.Date getEndTime() {
        return EndTime;
    }

    public void setEndTime(java.util.Date EndTime) {
        this.EndTime = EndTime;
    }

    public java.util.Date getPrintWarningTime() {
        return PrintWarningTime;
    }

    public void setPrintWarningTime(java.util.Date PrintWarningTime) {
        this.PrintWarningTime = PrintWarningTime;
    }

    public Integer getPrintBeginTime() {
        return PrintBeginTime;
    }

    public void setPrintBeginTime(Integer PrintBeginTime) {
        this.PrintBeginTime = PrintBeginTime;
    }

    public Integer getAlreadyCalculateStock() {
        return AlreadyCalculateStock;
    }

    public void setAlreadyCalculateStock(Integer AlreadyCalculateStock) {
        this.AlreadyCalculateStock = AlreadyCalculateStock;
    }

    public Integer getAlreadyExportToHQ() {
        return AlreadyExportToHQ;
    }

    public void setAlreadyExportToHQ(Integer AlreadyExportToHQ) {
        this.AlreadyExportToHQ = AlreadyExportToHQ;
    }

    public Integer getTableID() {
        return TableID;
    }

    public void setTableID(Integer TableID) {
        this.TableID = TableID;
    }

    public Integer getIsSplitTransaction() {
        return IsSplitTransaction;
    }

    public void setIsSplitTransaction(Integer IsSplitTransaction) {
        this.IsSplitTransaction = IsSplitTransaction;
    }

    public Integer getIsFromOtherTransaction() {
        return IsFromOtherTransaction;
    }

    public void setIsFromOtherTransaction(Integer IsFromOtherTransaction) {
        this.IsFromOtherTransaction = IsFromOtherTransaction;
    }

    public String getReferenceNo() {
        return ReferenceNo;
    }

    public void setReferenceNo(String ReferenceNo) {
        this.ReferenceNo = ReferenceNo;
    }

    public Integer getFromDepositTransactionID() {
        return FromDepositTransactionID;
    }

    public void setFromDepositTransactionID(Integer FromDepositTransactionID) {
        this.FromDepositTransactionID = FromDepositTransactionID;
    }

    public Integer getFromDepositComputerID() {
        return FromDepositComputerID;
    }

    public void setFromDepositComputerID(Integer FromDepositComputerID) {
        this.FromDepositComputerID = FromDepositComputerID;
    }

    public Integer getDeleted() {
        return Deleted;
    }

    public void setDeleted(Integer Deleted) {
        this.Deleted = Deleted;
    }

}
