package com.vtec.j1tth4.vtecpos.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PRODUCT_PRICE_GROUP_DATA.
*/
public class ProductPriceGroupDataDao extends AbstractDao<ProductPriceGroupData, Integer> {

    public static final String TABLENAME = "PRODUCT_PRICE_GROUP_DATA";

    /**
     * Properties of entity ProductPriceGroupData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PriceGroupDateID = new Property(0, int.class, "PriceGroupDateID", true, "PRICE_GROUP_DATE_ID");
        public final static Property PriceGroupID = new Property(1, int.class, "PriceGroupID", false, "PRICE_GROUP_ID");
        public final static Property ProductPriceID = new Property(2, int.class, "ProductPriceID", false, "PRODUCT_PRICE_ID");
        public final static Property ProductID = new Property(3, Integer.class, "ProductID", false, "PRODUCT_ID");
        public final static Property ProductPrice = new Property(4, Double.class, "ProductPrice", false, "PRODUCT_PRICE");
        public final static Property PrepaidPrice = new Property(5, double.class, "PrepaidPrice", false, "PREPAID_PRICE");
        public final static Property MainPrice = new Property(6, int.class, "MainPrice", false, "MAIN_PRICE");
        public final static Property SaleMode = new Property(7, int.class, "SaleMode", false, "SALE_MODE");
        public final static Property PriceRemark = new Property(8, String.class, "PriceRemark", false, "PRICE_REMARK");
        public final static Property AddingFromBranch = new Property(9, int.class, "AddingFromBranch", false, "ADDING_FROM_BRANCH");
    };


    public ProductPriceGroupDataDao(DaoConfig config) {
        super(config);
    }
    
    public ProductPriceGroupDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ProductPriceGroupData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPriceGroupDateID());
        stmt.bindLong(2, entity.getPriceGroupID());
        stmt.bindLong(3, entity.getProductPriceID());
 
        Integer ProductID = entity.getProductID();
        if (ProductID != null) {
            stmt.bindLong(4, ProductID);
        }
 
        Double ProductPrice = entity.getProductPrice();
        if (ProductPrice != null) {
            stmt.bindDouble(5, ProductPrice);
        }
        stmt.bindDouble(6, entity.getPrepaidPrice());
        stmt.bindLong(7, entity.getMainPrice());
        stmt.bindLong(8, entity.getSaleMode());
 
        String PriceRemark = entity.getPriceRemark();
        if (PriceRemark != null) {
            stmt.bindString(9, PriceRemark);
        }
        stmt.bindLong(10, entity.getAddingFromBranch());
    }

    /** @inheritdoc */
    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ProductPriceGroupData readEntity(Cursor cursor, int offset) {
        ProductPriceGroupData entity = new ProductPriceGroupData( //
            cursor.getInt(offset + 0), // PriceGroupDateID
            cursor.getInt(offset + 1), // PriceGroupID
            cursor.getInt(offset + 2), // ProductPriceID
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // ProductID
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // ProductPrice
            cursor.getDouble(offset + 5), // PrepaidPrice
            cursor.getInt(offset + 6), // MainPrice
            cursor.getInt(offset + 7), // SaleMode
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // PriceRemark
            cursor.getInt(offset + 9) // AddingFromBranch
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ProductPriceGroupData entity, int offset) {
        entity.setPriceGroupDateID(cursor.getInt(offset + 0));
        entity.setPriceGroupID(cursor.getInt(offset + 1));
        entity.setProductPriceID(cursor.getInt(offset + 2));
        entity.setProductID(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setProductPrice(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setPrepaidPrice(cursor.getDouble(offset + 5));
        entity.setMainPrice(cursor.getInt(offset + 6));
        entity.setSaleMode(cursor.getInt(offset + 7));
        entity.setPriceRemark(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setAddingFromBranch(cursor.getInt(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Integer updateKeyAfterInsert(ProductPriceGroupData entity, long rowId) {
        return entity.getPriceGroupDateID();
    }
    
    /** @inheritdoc */
    @Override
    public Integer getKey(ProductPriceGroupData entity) {
        if(entity != null) {
            return entity.getPriceGroupDateID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
