package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCT_TYPE.
 */
public class ProductType {

    private int ProductTypeID;
    private String ProductTypeName;
    private int ComponentLevel;
    private int ShowInFront;
    private int AutoAddMaterial;
    private int NotInRevenue;
    private int WeightPriceForRevenue;
    private int DisplayOrdering;
    private int Deleted;

    public ProductType() {
    }

    public ProductType(int ProductTypeID) {
        this.ProductTypeID = ProductTypeID;
    }

    public ProductType(int ProductTypeID, String ProductTypeName, int ComponentLevel, int ShowInFront, int AutoAddMaterial, int NotInRevenue, int WeightPriceForRevenue, int DisplayOrdering, int Deleted) {
        this.ProductTypeID = ProductTypeID;
        this.ProductTypeName = ProductTypeName;
        this.ComponentLevel = ComponentLevel;
        this.ShowInFront = ShowInFront;
        this.AutoAddMaterial = AutoAddMaterial;
        this.NotInRevenue = NotInRevenue;
        this.WeightPriceForRevenue = WeightPriceForRevenue;
        this.DisplayOrdering = DisplayOrdering;
        this.Deleted = Deleted;
    }

    public int getProductTypeID() {
        return ProductTypeID;
    }

    public void setProductTypeID(int ProductTypeID) {
        this.ProductTypeID = ProductTypeID;
    }

    public String getProductTypeName() {
        return ProductTypeName;
    }

    public void setProductTypeName(String ProductTypeName) {
        this.ProductTypeName = ProductTypeName;
    }

    public int getComponentLevel() {
        return ComponentLevel;
    }

    public void setComponentLevel(int ComponentLevel) {
        this.ComponentLevel = ComponentLevel;
    }

    public int getShowInFront() {
        return ShowInFront;
    }

    public void setShowInFront(int ShowInFront) {
        this.ShowInFront = ShowInFront;
    }

    public int getAutoAddMaterial() {
        return AutoAddMaterial;
    }

    public void setAutoAddMaterial(int AutoAddMaterial) {
        this.AutoAddMaterial = AutoAddMaterial;
    }

    public int getNotInRevenue() {
        return NotInRevenue;
    }

    public void setNotInRevenue(int NotInRevenue) {
        this.NotInRevenue = NotInRevenue;
    }

    public int getWeightPriceForRevenue() {
        return WeightPriceForRevenue;
    }

    public void setWeightPriceForRevenue(int WeightPriceForRevenue) {
        this.WeightPriceForRevenue = WeightPriceForRevenue;
    }

    public int getDisplayOrdering() {
        return DisplayOrdering;
    }

    public void setDisplayOrdering(int DisplayOrdering) {
        this.DisplayOrdering = DisplayOrdering;
    }

    public int getDeleted() {
        return Deleted;
    }

    public void setDeleted(int Deleted) {
        this.Deleted = Deleted;
    }

}
