package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ProductType.
 */
public class ProductType {

    private Integer ProductTypeID;
    private String ProductTypeName;
    private Integer ComponentLevel;
    private Integer ShowInFront;
    private Integer ShowInReceipt;
    private Integer AutoAddMaterial;
    private Integer NotInRevenue;
    private Integer WeightPriceForRevenue;
    private Integer IsComment;
    private Integer DisplayOrdering;
    private Integer Deleted;

    public ProductType() {
    }

    public ProductType(Integer ProductTypeID) {
        this.ProductTypeID = ProductTypeID;
    }

    public ProductType(Integer ProductTypeID, String ProductTypeName, Integer ComponentLevel, Integer ShowInFront, Integer ShowInReceipt, Integer AutoAddMaterial, Integer NotInRevenue, Integer WeightPriceForRevenue, Integer IsComment, Integer DisplayOrdering, Integer Deleted) {
        this.ProductTypeID = ProductTypeID;
        this.ProductTypeName = ProductTypeName;
        this.ComponentLevel = ComponentLevel;
        this.ShowInFront = ShowInFront;
        this.ShowInReceipt = ShowInReceipt;
        this.AutoAddMaterial = AutoAddMaterial;
        this.NotInRevenue = NotInRevenue;
        this.WeightPriceForRevenue = WeightPriceForRevenue;
        this.IsComment = IsComment;
        this.DisplayOrdering = DisplayOrdering;
        this.Deleted = Deleted;
    }

    public Integer getProductTypeID() {
        return ProductTypeID;
    }

    public void setProductTypeID(Integer ProductTypeID) {
        this.ProductTypeID = ProductTypeID;
    }

    public String getProductTypeName() {
        return ProductTypeName;
    }

    public void setProductTypeName(String ProductTypeName) {
        this.ProductTypeName = ProductTypeName;
    }

    public Integer getComponentLevel() {
        return ComponentLevel;
    }

    public void setComponentLevel(Integer ComponentLevel) {
        this.ComponentLevel = ComponentLevel;
    }

    public Integer getShowInFront() {
        return ShowInFront;
    }

    public void setShowInFront(Integer ShowInFront) {
        this.ShowInFront = ShowInFront;
    }

    public Integer getShowInReceipt() {
        return ShowInReceipt;
    }

    public void setShowInReceipt(Integer ShowInReceipt) {
        this.ShowInReceipt = ShowInReceipt;
    }

    public Integer getAutoAddMaterial() {
        return AutoAddMaterial;
    }

    public void setAutoAddMaterial(Integer AutoAddMaterial) {
        this.AutoAddMaterial = AutoAddMaterial;
    }

    public Integer getNotInRevenue() {
        return NotInRevenue;
    }

    public void setNotInRevenue(Integer NotInRevenue) {
        this.NotInRevenue = NotInRevenue;
    }

    public Integer getWeightPriceForRevenue() {
        return WeightPriceForRevenue;
    }

    public void setWeightPriceForRevenue(Integer WeightPriceForRevenue) {
        this.WeightPriceForRevenue = WeightPriceForRevenue;
    }

    public Integer getIsComment() {
        return IsComment;
    }

    public void setIsComment(Integer IsComment) {
        this.IsComment = IsComment;
    }

    public Integer getDisplayOrdering() {
        return DisplayOrdering;
    }

    public void setDisplayOrdering(Integer DisplayOrdering) {
        this.DisplayOrdering = DisplayOrdering;
    }

    public Integer getDeleted() {
        return Deleted;
    }

    public void setDeleted(Integer Deleted) {
        this.Deleted = Deleted;
    }

}
