package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ProductVat.
 */
public class ProductVat {

    private Integer ProductVATID;
    private String ProductVATCode;
    private Double ProductVATPercent;
    private String VATDisplay;
    private String VATDesp;
    private Integer Deleted;

    public ProductVat() {
    }

    public ProductVat(Integer ProductVATID) {
        this.ProductVATID = ProductVATID;
    }

    public ProductVat(Integer ProductVATID, String ProductVATCode, Double ProductVATPercent, String VATDisplay, String VATDesp, Integer Deleted) {
        this.ProductVATID = ProductVATID;
        this.ProductVATCode = ProductVATCode;
        this.ProductVATPercent = ProductVATPercent;
        this.VATDisplay = VATDisplay;
        this.VATDesp = VATDesp;
        this.Deleted = Deleted;
    }

    public Integer getProductVATID() {
        return ProductVATID;
    }

    public void setProductVATID(Integer ProductVATID) {
        this.ProductVATID = ProductVATID;
    }

    public String getProductVATCode() {
        return ProductVATCode;
    }

    public void setProductVATCode(String ProductVATCode) {
        this.ProductVATCode = ProductVATCode;
    }

    public Double getProductVATPercent() {
        return ProductVATPercent;
    }

    public void setProductVATPercent(Double ProductVATPercent) {
        this.ProductVATPercent = ProductVATPercent;
    }

    public String getVATDisplay() {
        return VATDisplay;
    }

    public void setVATDisplay(String VATDisplay) {
        this.VATDisplay = VATDisplay;
    }

    public String getVATDesp() {
        return VATDesp;
    }

    public void setVATDesp(String VATDesp) {
        this.VATDesp = VATDesp;
    }

    public Integer getDeleted() {
        return Deleted;
    }

    public void setDeleted(Integer Deleted) {
        this.Deleted = Deleted;
    }

}
