package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ProductDept.
 */
public class ProductDept {

    private int ProductDeptID;
    private int ProductGroupID;
    private int ShopID;
    private String ProductDeptCode;
    private String ProductDeptName;
    private String ProductDeptNameLang1;
    private String ProductDeptNameLang2;
    private String ProductDeptNameLang3;
    private String ProductDeptNameLang4;
    private String ProductDeptNameLang5;
    private int ProductDeptActivate;
    private int ProductDeptSaleMode;
    private int ProductDeptOrdering;
    private int PrintProductForSession;
    private Integer PrintReceiptGroupingDept;
    private int DisplayMobile;
    private int AddingFromBranch;
    private int Deleted;

    public ProductDept() {
    }

    public ProductDept(int ProductDeptID) {
        this.ProductDeptID = ProductDeptID;
    }

    public ProductDept(int ProductDeptID, int ProductGroupID, int ShopID, String ProductDeptCode, String ProductDeptName, String ProductDeptNameLang1, String ProductDeptNameLang2, String ProductDeptNameLang3, String ProductDeptNameLang4, String ProductDeptNameLang5, int ProductDeptActivate, int ProductDeptSaleMode, int ProductDeptOrdering, int PrintProductForSession, Integer PrintReceiptGroupingDept, int DisplayMobile, int AddingFromBranch, int Deleted) {
        this.ProductDeptID = ProductDeptID;
        this.ProductGroupID = ProductGroupID;
        this.ShopID = ShopID;
        this.ProductDeptCode = ProductDeptCode;
        this.ProductDeptName = ProductDeptName;
        this.ProductDeptNameLang1 = ProductDeptNameLang1;
        this.ProductDeptNameLang2 = ProductDeptNameLang2;
        this.ProductDeptNameLang3 = ProductDeptNameLang3;
        this.ProductDeptNameLang4 = ProductDeptNameLang4;
        this.ProductDeptNameLang5 = ProductDeptNameLang5;
        this.ProductDeptActivate = ProductDeptActivate;
        this.ProductDeptSaleMode = ProductDeptSaleMode;
        this.ProductDeptOrdering = ProductDeptOrdering;
        this.PrintProductForSession = PrintProductForSession;
        this.PrintReceiptGroupingDept = PrintReceiptGroupingDept;
        this.DisplayMobile = DisplayMobile;
        this.AddingFromBranch = AddingFromBranch;
        this.Deleted = Deleted;
    }

    public int getProductDeptID() {
        return ProductDeptID;
    }

    public void setProductDeptID(int ProductDeptID) {
        this.ProductDeptID = ProductDeptID;
    }

    public int getProductGroupID() {
        return ProductGroupID;
    }

    public void setProductGroupID(int ProductGroupID) {
        this.ProductGroupID = ProductGroupID;
    }

    public int getShopID() {
        return ShopID;
    }

    public void setShopID(int ShopID) {
        this.ShopID = ShopID;
    }

    public String getProductDeptCode() {
        return ProductDeptCode;
    }

    public void setProductDeptCode(String ProductDeptCode) {
        this.ProductDeptCode = ProductDeptCode;
    }

    public String getProductDeptName() {
        return ProductDeptName;
    }

    public void setProductDeptName(String ProductDeptName) {
        this.ProductDeptName = ProductDeptName;
    }

    public String getProductDeptNameLang1() {
        return ProductDeptNameLang1;
    }

    public void setProductDeptNameLang1(String ProductDeptNameLang1) {
        this.ProductDeptNameLang1 = ProductDeptNameLang1;
    }

    public String getProductDeptNameLang2() {
        return ProductDeptNameLang2;
    }

    public void setProductDeptNameLang2(String ProductDeptNameLang2) {
        this.ProductDeptNameLang2 = ProductDeptNameLang2;
    }

    public String getProductDeptNameLang3() {
        return ProductDeptNameLang3;
    }

    public void setProductDeptNameLang3(String ProductDeptNameLang3) {
        this.ProductDeptNameLang3 = ProductDeptNameLang3;
    }

    public String getProductDeptNameLang4() {
        return ProductDeptNameLang4;
    }

    public void setProductDeptNameLang4(String ProductDeptNameLang4) {
        this.ProductDeptNameLang4 = ProductDeptNameLang4;
    }

    public String getProductDeptNameLang5() {
        return ProductDeptNameLang5;
    }

    public void setProductDeptNameLang5(String ProductDeptNameLang5) {
        this.ProductDeptNameLang5 = ProductDeptNameLang5;
    }

    public int getProductDeptActivate() {
        return ProductDeptActivate;
    }

    public void setProductDeptActivate(int ProductDeptActivate) {
        this.ProductDeptActivate = ProductDeptActivate;
    }

    public int getProductDeptSaleMode() {
        return ProductDeptSaleMode;
    }

    public void setProductDeptSaleMode(int ProductDeptSaleMode) {
        this.ProductDeptSaleMode = ProductDeptSaleMode;
    }

    public int getProductDeptOrdering() {
        return ProductDeptOrdering;
    }

    public void setProductDeptOrdering(int ProductDeptOrdering) {
        this.ProductDeptOrdering = ProductDeptOrdering;
    }

    public int getPrintProductForSession() {
        return PrintProductForSession;
    }

    public void setPrintProductForSession(int PrintProductForSession) {
        this.PrintProductForSession = PrintProductForSession;
    }

    public Integer getPrintReceiptGroupingDept() {
        return PrintReceiptGroupingDept;
    }

    public void setPrintReceiptGroupingDept(Integer PrintReceiptGroupingDept) {
        this.PrintReceiptGroupingDept = PrintReceiptGroupingDept;
    }

    public int getDisplayMobile() {
        return DisplayMobile;
    }

    public void setDisplayMobile(int DisplayMobile) {
        this.DisplayMobile = DisplayMobile;
    }

    public int getAddingFromBranch() {
        return AddingFromBranch;
    }

    public void setAddingFromBranch(int AddingFromBranch) {
        this.AddingFromBranch = AddingFromBranch;
    }

    public int getDeleted() {
        return Deleted;
    }

    public void setDeleted(int Deleted) {
        this.Deleted = Deleted;
    }

}
