package com.vtec.j1tth4.vtecpos.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroup;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PRODUCT_PRICE_GROUP.
*/
public class ProductPriceGroupDao extends AbstractDao<ProductPriceGroup, Integer> {

    public static final String TABLENAME = "PRODUCT_PRICE_GROUP";

    /**
     * Properties of entity ProductPriceGroup.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PriceGroupID = new Property(0, int.class, "PriceGroupID", true, "PRICE_GROUP_ID");
        public final static Property PriceGroupName = new Property(1, String.class, "PriceGroupName", false, "PRICE_GROUP_NAME");
        public final static Property Deleted = new Property(2, int.class, "Deleted", false, "DELETED");
    };


    public ProductPriceGroupDao(DaoConfig config) {
        super(config);
    }
    
    public ProductPriceGroupDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PRODUCT_PRICE_GROUP' (" + //
                "'PRICE_GROUP_ID' INTEGER PRIMARY KEY NOT NULL ," + // 0: PriceGroupID
                "'PRICE_GROUP_NAME' TEXT," + // 1: PriceGroupName
                "'DELETED' INTEGER NOT NULL );"); // 2: Deleted
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PRODUCT_PRICE_GROUP'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ProductPriceGroup entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPriceGroupID());
 
        String PriceGroupName = entity.getPriceGroupName();
        if (PriceGroupName != null) {
            stmt.bindString(2, PriceGroupName);
        }
        stmt.bindLong(3, entity.getDeleted());
    }

    /** @inheritdoc */
    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ProductPriceGroup readEntity(Cursor cursor, int offset) {
        ProductPriceGroup entity = new ProductPriceGroup( //
            cursor.getInt(offset + 0), // PriceGroupID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // PriceGroupName
            cursor.getInt(offset + 2) // Deleted
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ProductPriceGroup entity, int offset) {
        entity.setPriceGroupID(cursor.getInt(offset + 0));
        entity.setPriceGroupName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDeleted(cursor.getInt(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Integer updateKeyAfterInsert(ProductPriceGroup entity, long rowId) {
        return entity.getPriceGroupID();
    }
    
    /** @inheritdoc */
    @Override
    public Integer getKey(ProductPriceGroup entity) {
        if(entity != null) {
            return entity.getPriceGroupID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
