package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCT_PRICE_GROUP.
 */
public class ProductPriceGroup {

    private int PriceGroupID;
    private String PriceGroupName;
    private int Deleted;

    public ProductPriceGroup() {
    }

    public ProductPriceGroup(int PriceGroupID) {
        this.PriceGroupID = PriceGroupID;
    }

    public ProductPriceGroup(int PriceGroupID, String PriceGroupName, int Deleted) {
        this.PriceGroupID = PriceGroupID;
        this.PriceGroupName = PriceGroupName;
        this.Deleted = Deleted;
    }

    public int getPriceGroupID() {
        return PriceGroupID;
    }

    public void setPriceGroupID(int PriceGroupID) {
        this.PriceGroupID = PriceGroupID;
    }

    public String getPriceGroupName() {
        return PriceGroupName;
    }

    public void setPriceGroupName(String PriceGroupName) {
        this.PriceGroupName = PriceGroupName;
    }

    public int getDeleted() {
        return Deleted;
    }

    public void setDeleted(int Deleted) {
        this.Deleted = Deleted;
    }

}
