package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCT_PRICE_GROUP_SHOP.
 */
public class ProductPriceGroupShop {

    private int PriceGroupID;
    private int ShopID;

    public ProductPriceGroupShop() {
    }

    public ProductPriceGroupShop(int PriceGroupID) {
        this.PriceGroupID = PriceGroupID;
    }

    public ProductPriceGroupShop(int PriceGroupID, int ShopID) {
        this.PriceGroupID = PriceGroupID;
        this.ShopID = ShopID;
    }

    public int getPriceGroupID() {
        return PriceGroupID;
    }

    public void setPriceGroupID(int PriceGroupID) {
        this.PriceGroupID = PriceGroupID;
    }

    public int getShopID() {
        return ShopID;
    }

    public void setShopID(int ShopID) {
        this.ShopID = ShopID;
    }

}
