package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCTS.
 */
public class Products {

    private int ProductID;
    private int ShopID;
    private int ProductGroupID;
    private int ProductDeptID;
    private int ProductCat1ID;
    private int ProductCat2ID;
    private int ProductCat3ID;
    private int ProductCat4ID;
    private int ProductCat5ID;
    private int ProductTypeID;
    private String ProductCode;
    private String ProductBarCode;
    /** Not-null value. */
    private String ProductName;
    private String ProductNameLang1;
    private String ProductNameLang2;
    private String ProductNameLang3;
    private String ProductNameLang4;
    private String ProductNameLang5;
    private String ProductMName;
    private String ProductMNameLang1;
    private String ProductMNameLang2;
    private String ProductMNameLang3;
    private String ProductMNameLang4;
    private String ProductMNameLang5;
    private String ProductPictureServer;
    private String ProductPictureClient;
    private int PrinterID;
    private int PrintGroup;
    private int DurationTime;
    private int HasServiceCharge;
    private int IsOutOfStock;
    private int AutoComment;
    private int CanReturnProduct;
    private int DisplayAtCheckerSystem;
    private java.util.Date ProductEnableDateTime;
    private java.util.Date ProductExpireDateTime;
    private String ProductEnableDayString;
    private int WarningTime;
    private int CriticalTime;
    private int SaleMode1;
    private int SaleMode2;
    private int SaleMode3;
    private int SaleMode4;
    private int SaleMode5;
    private int SaleMode6;
    private int SaleMode7;
    private int SaleMode8;
    private int SaleMode9;
    private int SaleMode10;
    private int VATType;
    /** Not-null value. */
    private String VATCode;
    private String ProductUnitName;
    private int DiscountAllow;
    private int ZeroPriceAllow;
    private double LimitDiscountAmount;
    private double LimitDiscountPercent;
    private int CommRate;
    private String ProductDesp;
    private int ProductDisplay;
    private int ProductActivate;
    private int ProductOrdering;
    private int PrintOrdering;
    private int AddingFromBranch;
    private int Deleted;
    private java.util.Date InsertDate;
    private java.util.Date UpdateDate;

    public Products() {
    }

    public Products(int ProductID) {
        this.ProductID = ProductID;
    }

    public Products(int ProductID, int ShopID, int ProductGroupID, int ProductDeptID, int ProductCat1ID, int ProductCat2ID, int ProductCat3ID, int ProductCat4ID, int ProductCat5ID, int ProductTypeID, String ProductCode, String ProductBarCode, String ProductName, String ProductNameLang1, String ProductNameLang2, String ProductNameLang3, String ProductNameLang4, String ProductNameLang5, String ProductMName, String ProductMNameLang1, String ProductMNameLang2, String ProductMNameLang3, String ProductMNameLang4, String ProductMNameLang5, String ProductPictureServer, String ProductPictureClient, int PrinterID, int PrintGroup, int DurationTime, int HasServiceCharge, int IsOutOfStock, int AutoComment, int CanReturnProduct, int DisplayAtCheckerSystem, java.util.Date ProductEnableDateTime, java.util.Date ProductExpireDateTime, String ProductEnableDayString, int WarningTime, int CriticalTime, int SaleMode1, int SaleMode2, int SaleMode3, int SaleMode4, int SaleMode5, int SaleMode6, int SaleMode7, int SaleMode8, int SaleMode9, int SaleMode10, int VATType, String VATCode, String ProductUnitName, int DiscountAllow, int ZeroPriceAllow, double LimitDiscountAmount, double LimitDiscountPercent, int CommRate, String ProductDesp, int ProductDisplay, int ProductActivate, int ProductOrdering, int PrintOrdering, int AddingFromBranch, int Deleted, java.util.Date InsertDate, java.util.Date UpdateDate) {
        this.ProductID = ProductID;
        this.ShopID = ShopID;
        this.ProductGroupID = ProductGroupID;
        this.ProductDeptID = ProductDeptID;
        this.ProductCat1ID = ProductCat1ID;
        this.ProductCat2ID = ProductCat2ID;
        this.ProductCat3ID = ProductCat3ID;
        this.ProductCat4ID = ProductCat4ID;
        this.ProductCat5ID = ProductCat5ID;
        this.ProductTypeID = ProductTypeID;
        this.ProductCode = ProductCode;
        this.ProductBarCode = ProductBarCode;
        this.ProductName = ProductName;
        this.ProductNameLang1 = ProductNameLang1;
        this.ProductNameLang2 = ProductNameLang2;
        this.ProductNameLang3 = ProductNameLang3;
        this.ProductNameLang4 = ProductNameLang4;
        this.ProductNameLang5 = ProductNameLang5;
        this.ProductMName = ProductMName;
        this.ProductMNameLang1 = ProductMNameLang1;
        this.ProductMNameLang2 = ProductMNameLang2;
        this.ProductMNameLang3 = ProductMNameLang3;
        this.ProductMNameLang4 = ProductMNameLang4;
        this.ProductMNameLang5 = ProductMNameLang5;
        this.ProductPictureServer = ProductPictureServer;
        this.ProductPictureClient = ProductPictureClient;
        this.PrinterID = PrinterID;
        this.PrintGroup = PrintGroup;
        this.DurationTime = DurationTime;
        this.HasServiceCharge = HasServiceCharge;
        this.IsOutOfStock = IsOutOfStock;
        this.AutoComment = AutoComment;
        this.CanReturnProduct = CanReturnProduct;
        this.DisplayAtCheckerSystem = DisplayAtCheckerSystem;
        this.ProductEnableDateTime = ProductEnableDateTime;
        this.ProductExpireDateTime = ProductExpireDateTime;
        this.ProductEnableDayString = ProductEnableDayString;
        this.WarningTime = WarningTime;
        this.CriticalTime = CriticalTime;
        this.SaleMode1 = SaleMode1;
        this.SaleMode2 = SaleMode2;
        this.SaleMode3 = SaleMode3;
        this.SaleMode4 = SaleMode4;
        this.SaleMode5 = SaleMode5;
        this.SaleMode6 = SaleMode6;
        this.SaleMode7 = SaleMode7;
        this.SaleMode8 = SaleMode8;
        this.SaleMode9 = SaleMode9;
        this.SaleMode10 = SaleMode10;
        this.VATType = VATType;
        this.VATCode = VATCode;
        this.ProductUnitName = ProductUnitName;
        this.DiscountAllow = DiscountAllow;
        this.ZeroPriceAllow = ZeroPriceAllow;
        this.LimitDiscountAmount = LimitDiscountAmount;
        this.LimitDiscountPercent = LimitDiscountPercent;
        this.CommRate = CommRate;
        this.ProductDesp = ProductDesp;
        this.ProductDisplay = ProductDisplay;
        this.ProductActivate = ProductActivate;
        this.ProductOrdering = ProductOrdering;
        this.PrintOrdering = PrintOrdering;
        this.AddingFromBranch = AddingFromBranch;
        this.Deleted = Deleted;
        this.InsertDate = InsertDate;
        this.UpdateDate = UpdateDate;
    }

    public int getProductID() {
        return ProductID;
    }

    public void setProductID(int ProductID) {
        this.ProductID = ProductID;
    }

    public int getShopID() {
        return ShopID;
    }

    public void setShopID(int ShopID) {
        this.ShopID = ShopID;
    }

    public int getProductGroupID() {
        return ProductGroupID;
    }

    public void setProductGroupID(int ProductGroupID) {
        this.ProductGroupID = ProductGroupID;
    }

    public int getProductDeptID() {
        return ProductDeptID;
    }

    public void setProductDeptID(int ProductDeptID) {
        this.ProductDeptID = ProductDeptID;
    }

    public int getProductCat1ID() {
        return ProductCat1ID;
    }

    public void setProductCat1ID(int ProductCat1ID) {
        this.ProductCat1ID = ProductCat1ID;
    }

    public int getProductCat2ID() {
        return ProductCat2ID;
    }

    public void setProductCat2ID(int ProductCat2ID) {
        this.ProductCat2ID = ProductCat2ID;
    }

    public int getProductCat3ID() {
        return ProductCat3ID;
    }

    public void setProductCat3ID(int ProductCat3ID) {
        this.ProductCat3ID = ProductCat3ID;
    }

    public int getProductCat4ID() {
        return ProductCat4ID;
    }

    public void setProductCat4ID(int ProductCat4ID) {
        this.ProductCat4ID = ProductCat4ID;
    }

    public int getProductCat5ID() {
        return ProductCat5ID;
    }

    public void setProductCat5ID(int ProductCat5ID) {
        this.ProductCat5ID = ProductCat5ID;
    }

    public int getProductTypeID() {
        return ProductTypeID;
    }

    public void setProductTypeID(int ProductTypeID) {
        this.ProductTypeID = ProductTypeID;
    }

    public String getProductCode() {
        return ProductCode;
    }

    public void setProductCode(String ProductCode) {
        this.ProductCode = ProductCode;
    }

    public String getProductBarCode() {
        return ProductBarCode;
    }

    public void setProductBarCode(String ProductBarCode) {
        this.ProductBarCode = ProductBarCode;
    }

    /** Not-null value. */
    public String getProductName() {
        return ProductName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProductName(String ProductName) {
        this.ProductName = ProductName;
    }

    public String getProductNameLang1() {
        return ProductNameLang1;
    }

    public void setProductNameLang1(String ProductNameLang1) {
        this.ProductNameLang1 = ProductNameLang1;
    }

    public String getProductNameLang2() {
        return ProductNameLang2;
    }

    public void setProductNameLang2(String ProductNameLang2) {
        this.ProductNameLang2 = ProductNameLang2;
    }

    public String getProductNameLang3() {
        return ProductNameLang3;
    }

    public void setProductNameLang3(String ProductNameLang3) {
        this.ProductNameLang3 = ProductNameLang3;
    }

    public String getProductNameLang4() {
        return ProductNameLang4;
    }

    public void setProductNameLang4(String ProductNameLang4) {
        this.ProductNameLang4 = ProductNameLang4;
    }

    public String getProductNameLang5() {
        return ProductNameLang5;
    }

    public void setProductNameLang5(String ProductNameLang5) {
        this.ProductNameLang5 = ProductNameLang5;
    }

    public String getProductMName() {
        return ProductMName;
    }

    public void setProductMName(String ProductMName) {
        this.ProductMName = ProductMName;
    }

    public String getProductMNameLang1() {
        return ProductMNameLang1;
    }

    public void setProductMNameLang1(String ProductMNameLang1) {
        this.ProductMNameLang1 = ProductMNameLang1;
    }

    public String getProductMNameLang2() {
        return ProductMNameLang2;
    }

    public void setProductMNameLang2(String ProductMNameLang2) {
        this.ProductMNameLang2 = ProductMNameLang2;
    }

    public String getProductMNameLang3() {
        return ProductMNameLang3;
    }

    public void setProductMNameLang3(String ProductMNameLang3) {
        this.ProductMNameLang3 = ProductMNameLang3;
    }

    public String getProductMNameLang4() {
        return ProductMNameLang4;
    }

    public void setProductMNameLang4(String ProductMNameLang4) {
        this.ProductMNameLang4 = ProductMNameLang4;
    }

    public String getProductMNameLang5() {
        return ProductMNameLang5;
    }

    public void setProductMNameLang5(String ProductMNameLang5) {
        this.ProductMNameLang5 = ProductMNameLang5;
    }

    public String getProductPictureServer() {
        return ProductPictureServer;
    }

    public void setProductPictureServer(String ProductPictureServer) {
        this.ProductPictureServer = ProductPictureServer;
    }

    public String getProductPictureClient() {
        return ProductPictureClient;
    }

    public void setProductPictureClient(String ProductPictureClient) {
        this.ProductPictureClient = ProductPictureClient;
    }

    public int getPrinterID() {
        return PrinterID;
    }

    public void setPrinterID(int PrinterID) {
        this.PrinterID = PrinterID;
    }

    public int getPrintGroup() {
        return PrintGroup;
    }

    public void setPrintGroup(int PrintGroup) {
        this.PrintGroup = PrintGroup;
    }

    public int getDurationTime() {
        return DurationTime;
    }

    public void setDurationTime(int DurationTime) {
        this.DurationTime = DurationTime;
    }

    public int getHasServiceCharge() {
        return HasServiceCharge;
    }

    public void setHasServiceCharge(int HasServiceCharge) {
        this.HasServiceCharge = HasServiceCharge;
    }

    public int getIsOutOfStock() {
        return IsOutOfStock;
    }

    public void setIsOutOfStock(int IsOutOfStock) {
        this.IsOutOfStock = IsOutOfStock;
    }

    public int getAutoComment() {
        return AutoComment;
    }

    public void setAutoComment(int AutoComment) {
        this.AutoComment = AutoComment;
    }

    public int getCanReturnProduct() {
        return CanReturnProduct;
    }

    public void setCanReturnProduct(int CanReturnProduct) {
        this.CanReturnProduct = CanReturnProduct;
    }

    public int getDisplayAtCheckerSystem() {
        return DisplayAtCheckerSystem;
    }

    public void setDisplayAtCheckerSystem(int DisplayAtCheckerSystem) {
        this.DisplayAtCheckerSystem = DisplayAtCheckerSystem;
    }

    public java.util.Date getProductEnableDateTime() {
        return ProductEnableDateTime;
    }

    public void setProductEnableDateTime(java.util.Date ProductEnableDateTime) {
        this.ProductEnableDateTime = ProductEnableDateTime;
    }

    public java.util.Date getProductExpireDateTime() {
        return ProductExpireDateTime;
    }

    public void setProductExpireDateTime(java.util.Date ProductExpireDateTime) {
        this.ProductExpireDateTime = ProductExpireDateTime;
    }

    public String getProductEnableDayString() {
        return ProductEnableDayString;
    }

    public void setProductEnableDayString(String ProductEnableDayString) {
        this.ProductEnableDayString = ProductEnableDayString;
    }

    public int getWarningTime() {
        return WarningTime;
    }

    public void setWarningTime(int WarningTime) {
        this.WarningTime = WarningTime;
    }

    public int getCriticalTime() {
        return CriticalTime;
    }

    public void setCriticalTime(int CriticalTime) {
        this.CriticalTime = CriticalTime;
    }

    public int getSaleMode1() {
        return SaleMode1;
    }

    public void setSaleMode1(int SaleMode1) {
        this.SaleMode1 = SaleMode1;
    }

    public int getSaleMode2() {
        return SaleMode2;
    }

    public void setSaleMode2(int SaleMode2) {
        this.SaleMode2 = SaleMode2;
    }

    public int getSaleMode3() {
        return SaleMode3;
    }

    public void setSaleMode3(int SaleMode3) {
        this.SaleMode3 = SaleMode3;
    }

    public int getSaleMode4() {
        return SaleMode4;
    }

    public void setSaleMode4(int SaleMode4) {
        this.SaleMode4 = SaleMode4;
    }

    public int getSaleMode5() {
        return SaleMode5;
    }

    public void setSaleMode5(int SaleMode5) {
        this.SaleMode5 = SaleMode5;
    }

    public int getSaleMode6() {
        return SaleMode6;
    }

    public void setSaleMode6(int SaleMode6) {
        this.SaleMode6 = SaleMode6;
    }

    public int getSaleMode7() {
        return SaleMode7;
    }

    public void setSaleMode7(int SaleMode7) {
        this.SaleMode7 = SaleMode7;
    }

    public int getSaleMode8() {
        return SaleMode8;
    }

    public void setSaleMode8(int SaleMode8) {
        this.SaleMode8 = SaleMode8;
    }

    public int getSaleMode9() {
        return SaleMode9;
    }

    public void setSaleMode9(int SaleMode9) {
        this.SaleMode9 = SaleMode9;
    }

    public int getSaleMode10() {
        return SaleMode10;
    }

    public void setSaleMode10(int SaleMode10) {
        this.SaleMode10 = SaleMode10;
    }

    public int getVATType() {
        return VATType;
    }

    public void setVATType(int VATType) {
        this.VATType = VATType;
    }

    /** Not-null value. */
    public String getVATCode() {
        return VATCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVATCode(String VATCode) {
        this.VATCode = VATCode;
    }

    public String getProductUnitName() {
        return ProductUnitName;
    }

    public void setProductUnitName(String ProductUnitName) {
        this.ProductUnitName = ProductUnitName;
    }

    public int getDiscountAllow() {
        return DiscountAllow;
    }

    public void setDiscountAllow(int DiscountAllow) {
        this.DiscountAllow = DiscountAllow;
    }

    public int getZeroPriceAllow() {
        return ZeroPriceAllow;
    }

    public void setZeroPriceAllow(int ZeroPriceAllow) {
        this.ZeroPriceAllow = ZeroPriceAllow;
    }

    public double getLimitDiscountAmount() {
        return LimitDiscountAmount;
    }

    public void setLimitDiscountAmount(double LimitDiscountAmount) {
        this.LimitDiscountAmount = LimitDiscountAmount;
    }

    public double getLimitDiscountPercent() {
        return LimitDiscountPercent;
    }

    public void setLimitDiscountPercent(double LimitDiscountPercent) {
        this.LimitDiscountPercent = LimitDiscountPercent;
    }

    public int getCommRate() {
        return CommRate;
    }

    public void setCommRate(int CommRate) {
        this.CommRate = CommRate;
    }

    public String getProductDesp() {
        return ProductDesp;
    }

    public void setProductDesp(String ProductDesp) {
        this.ProductDesp = ProductDesp;
    }

    public int getProductDisplay() {
        return ProductDisplay;
    }

    public void setProductDisplay(int ProductDisplay) {
        this.ProductDisplay = ProductDisplay;
    }

    public int getProductActivate() {
        return ProductActivate;
    }

    public void setProductActivate(int ProductActivate) {
        this.ProductActivate = ProductActivate;
    }

    public int getProductOrdering() {
        return ProductOrdering;
    }

    public void setProductOrdering(int ProductOrdering) {
        this.ProductOrdering = ProductOrdering;
    }

    public int getPrintOrdering() {
        return PrintOrdering;
    }

    public void setPrintOrdering(int PrintOrdering) {
        this.PrintOrdering = PrintOrdering;
    }

    public int getAddingFromBranch() {
        return AddingFromBranch;
    }

    public void setAddingFromBranch(int AddingFromBranch) {
        this.AddingFromBranch = AddingFromBranch;
    }

    public int getDeleted() {
        return Deleted;
    }

    public void setDeleted(int Deleted) {
        this.Deleted = Deleted;
    }

    public java.util.Date getInsertDate() {
        return InsertDate;
    }

    public void setInsertDate(java.util.Date InsertDate) {
        this.InsertDate = InsertDate;
    }

    public java.util.Date getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(java.util.Date UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

}
