package com.vtec.j1tth4.vtecpos.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.vtec.j1tth4.vtecpos.dao.ProductPriceGroupShop;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ProductPriceGroupShop.
*/
public class ProductPriceGroupShopDao extends AbstractDao<ProductPriceGroupShop, Void> {

    public static final String TABLENAME = "ProductPriceGroupShop";

    /**
     * Properties of entity ProductPriceGroupShop.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PriceGroupID = new Property(0, Integer.class, "PriceGroupID", true, "PriceGroupID");
        public final static Property ShopID = new Property(1, Integer.class, "ShopID", true, "ShopID");
    };


    public ProductPriceGroupShopDao(DaoConfig config) {
        super(config);
    }
    
    public ProductPriceGroupShopDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ProductPriceGroupShop entity) {
        stmt.clearBindings();
 
        Integer PriceGroupID = entity.getPriceGroupID();
        if (PriceGroupID != null) {
            stmt.bindLong(1, PriceGroupID);
        }
 
        Integer ShopID = entity.getShopID();
        if (ShopID != null) {
            stmt.bindLong(2, ShopID);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public ProductPriceGroupShop readEntity(Cursor cursor, int offset) {
        ProductPriceGroupShop entity = new ProductPriceGroupShop( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // PriceGroupID
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1) // ShopID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ProductPriceGroupShop entity, int offset) {
        entity.setPriceGroupID(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setShopID(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(ProductPriceGroupShop entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(ProductPriceGroupShop entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
