package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCTS.
 */
public class Products {

    private int ProductID;
    private int ShopID;
    private Integer InventoryID;
    private Integer ProductGroupID;
    private Integer ProductDeptID;
    private Integer ProductCat1ID;
    private Integer ProductCat2ID;
    private Integer ProductCat3ID;
    private Integer ProductCat4ID;
    private Integer ProductCat5ID;
    private Integer ProductTypeID;
    private String ProductCode;
    private String ProductBarCode;
    private String ProductName;
    private String ProductNameLang1;
    private String ProductNameLang2;
    private String ProductNameLang3;
    private String ProductNameLang4;
    private String ProductNameLang5;
    private String ProductMName;
    private String ProductMNameLang1;
    private String ProductMNameLang2;
    private String ProductMNameLang3;
    private String ProductMNameLang4;
    private String ProductMNameLang5;
    private String ProductPictureServer;
    private String ProductPictureClient;
    private Integer PrinterID;
    private Integer PrintGroup;
    private String PrintProductName;
    private java.util.Date DurationTime;
    private Integer HasServiceCharge;
    private Integer IsOutOfStock;
    private Integer AutoComment;
    private Integer IsDisplayBill;
    private Integer IsPrintCheck;
    private Integer IsPrintReceipt;
    private Integer CanReturnProduct;
    private Integer DisplayAtCheckerSystem;
    private java.util.Date ProductEnableDateTime;
    private java.util.Date ProductExpireDateTime;
    private java.util.Date ProductEnableDayString;
    private java.util.Date WarningTime;
    private java.util.Date CriticalTime;
    private Integer SaleMode1;
    private Integer SaleMode2;
    private Integer SaleMode3;
    private Integer SaleMode4;
    private Integer SaleMode5;
    private Integer SaleMode6;
    private Integer SaleMode7;
    private Integer SaleMode8;
    private Integer SaleMode9;
    private Integer SaleMode10;
    private Integer VATType;
    private String VATCode;
    private String ProductUnitName;
    private Integer DiscountAllow;
    private Integer ZeroPriceAllow;
    private Integer LimitDiscountAmount;
    private Integer LimitDiscountPercent;
    private Integer CommRate;
    private String ProductDesp;
    private Integer ProductDisplay;
    private Integer ProductActivate;
    private Integer ProductOrdering;
    private Integer PrintOrdering;
    private Integer AddingFromBranch;
    private Integer Deleted;
    private java.util.Date InsertDate;
    private java.util.Date UpdateDate;

    public Products() {
    }

    public Products(int ProductID) {
        this.ProductID = ProductID;
    }

    public Products(int ProductID, int ShopID, Integer InventoryID, Integer ProductGroupID, Integer ProductDeptID, Integer ProductCat1ID, Integer ProductCat2ID, Integer ProductCat3ID, Integer ProductCat4ID, Integer ProductCat5ID, Integer ProductTypeID, String ProductCode, String ProductBarCode, String ProductName, String ProductNameLang1, String ProductNameLang2, String ProductNameLang3, String ProductNameLang4, String ProductNameLang5, String ProductMName, String ProductMNameLang1, String ProductMNameLang2, String ProductMNameLang3, String ProductMNameLang4, String ProductMNameLang5, String ProductPictureServer, String ProductPictureClient, Integer PrinterID, Integer PrintGroup, String PrintProductName, java.util.Date DurationTime, Integer HasServiceCharge, Integer IsOutOfStock, Integer AutoComment, Integer IsDisplayBill, Integer IsPrintCheck, Integer IsPrintReceipt, Integer CanReturnProduct, Integer DisplayAtCheckerSystem, java.util.Date ProductEnableDateTime, java.util.Date ProductExpireDateTime, java.util.Date ProductEnableDayString, java.util.Date WarningTime, java.util.Date CriticalTime, Integer SaleMode1, Integer SaleMode2, Integer SaleMode3, Integer SaleMode4, Integer SaleMode5, Integer SaleMode6, Integer SaleMode7, Integer SaleMode8, Integer SaleMode9, Integer SaleMode10, Integer VATType, String VATCode, String ProductUnitName, Integer DiscountAllow, Integer ZeroPriceAllow, Integer LimitDiscountAmount, Integer LimitDiscountPercent, Integer CommRate, String ProductDesp, Integer ProductDisplay, Integer ProductActivate, Integer ProductOrdering, Integer PrintOrdering, Integer AddingFromBranch, Integer Deleted, java.util.Date InsertDate, java.util.Date UpdateDate) {
        this.ProductID = ProductID;
        this.ShopID = ShopID;
        this.InventoryID = InventoryID;
        this.ProductGroupID = ProductGroupID;
        this.ProductDeptID = ProductDeptID;
        this.ProductCat1ID = ProductCat1ID;
        this.ProductCat2ID = ProductCat2ID;
        this.ProductCat3ID = ProductCat3ID;
        this.ProductCat4ID = ProductCat4ID;
        this.ProductCat5ID = ProductCat5ID;
        this.ProductTypeID = ProductTypeID;
        this.ProductCode = ProductCode;
        this.ProductBarCode = ProductBarCode;
        this.ProductName = ProductName;
        this.ProductNameLang1 = ProductNameLang1;
        this.ProductNameLang2 = ProductNameLang2;
        this.ProductNameLang3 = ProductNameLang3;
        this.ProductNameLang4 = ProductNameLang4;
        this.ProductNameLang5 = ProductNameLang5;
        this.ProductMName = ProductMName;
        this.ProductMNameLang1 = ProductMNameLang1;
        this.ProductMNameLang2 = ProductMNameLang2;
        this.ProductMNameLang3 = ProductMNameLang3;
        this.ProductMNameLang4 = ProductMNameLang4;
        this.ProductMNameLang5 = ProductMNameLang5;
        this.ProductPictureServer = ProductPictureServer;
        this.ProductPictureClient = ProductPictureClient;
        this.PrinterID = PrinterID;
        this.PrintGroup = PrintGroup;
        this.PrintProductName = PrintProductName;
        this.DurationTime = DurationTime;
        this.HasServiceCharge = HasServiceCharge;
        this.IsOutOfStock = IsOutOfStock;
        this.AutoComment = AutoComment;
        this.IsDisplayBill = IsDisplayBill;
        this.IsPrintCheck = IsPrintCheck;
        this.IsPrintReceipt = IsPrintReceipt;
        this.CanReturnProduct = CanReturnProduct;
        this.DisplayAtCheckerSystem = DisplayAtCheckerSystem;
        this.ProductEnableDateTime = ProductEnableDateTime;
        this.ProductExpireDateTime = ProductExpireDateTime;
        this.ProductEnableDayString = ProductEnableDayString;
        this.WarningTime = WarningTime;
        this.CriticalTime = CriticalTime;
        this.SaleMode1 = SaleMode1;
        this.SaleMode2 = SaleMode2;
        this.SaleMode3 = SaleMode3;
        this.SaleMode4 = SaleMode4;
        this.SaleMode5 = SaleMode5;
        this.SaleMode6 = SaleMode6;
        this.SaleMode7 = SaleMode7;
        this.SaleMode8 = SaleMode8;
        this.SaleMode9 = SaleMode9;
        this.SaleMode10 = SaleMode10;
        this.VATType = VATType;
        this.VATCode = VATCode;
        this.ProductUnitName = ProductUnitName;
        this.DiscountAllow = DiscountAllow;
        this.ZeroPriceAllow = ZeroPriceAllow;
        this.LimitDiscountAmount = LimitDiscountAmount;
        this.LimitDiscountPercent = LimitDiscountPercent;
        this.CommRate = CommRate;
        this.ProductDesp = ProductDesp;
        this.ProductDisplay = ProductDisplay;
        this.ProductActivate = ProductActivate;
        this.ProductOrdering = ProductOrdering;
        this.PrintOrdering = PrintOrdering;
        this.AddingFromBranch = AddingFromBranch;
        this.Deleted = Deleted;
        this.InsertDate = InsertDate;
        this.UpdateDate = UpdateDate;
    }

    public int getProductID() {
        return ProductID;
    }

    public void setProductID(int ProductID) {
        this.ProductID = ProductID;
    }

    public int getShopID() {
        return ShopID;
    }

    public void setShopID(int ShopID) {
        this.ShopID = ShopID;
    }

    public Integer getInventoryID() {
        return InventoryID;
    }

    public void setInventoryID(Integer InventoryID) {
        this.InventoryID = InventoryID;
    }

    public Integer getProductGroupID() {
        return ProductGroupID;
    }

    public void setProductGroupID(Integer ProductGroupID) {
        this.ProductGroupID = ProductGroupID;
    }

    public Integer getProductDeptID() {
        return ProductDeptID;
    }

    public void setProductDeptID(Integer ProductDeptID) {
        this.ProductDeptID = ProductDeptID;
    }

    public Integer getProductCat1ID() {
        return ProductCat1ID;
    }

    public void setProductCat1ID(Integer ProductCat1ID) {
        this.ProductCat1ID = ProductCat1ID;
    }

    public Integer getProductCat2ID() {
        return ProductCat2ID;
    }

    public void setProductCat2ID(Integer ProductCat2ID) {
        this.ProductCat2ID = ProductCat2ID;
    }

    public Integer getProductCat3ID() {
        return ProductCat3ID;
    }

    public void setProductCat3ID(Integer ProductCat3ID) {
        this.ProductCat3ID = ProductCat3ID;
    }

    public Integer getProductCat4ID() {
        return ProductCat4ID;
    }

    public void setProductCat4ID(Integer ProductCat4ID) {
        this.ProductCat4ID = ProductCat4ID;
    }

    public Integer getProductCat5ID() {
        return ProductCat5ID;
    }

    public void setProductCat5ID(Integer ProductCat5ID) {
        this.ProductCat5ID = ProductCat5ID;
    }

    public Integer getProductTypeID() {
        return ProductTypeID;
    }

    public void setProductTypeID(Integer ProductTypeID) {
        this.ProductTypeID = ProductTypeID;
    }

    public String getProductCode() {
        return ProductCode;
    }

    public void setProductCode(String ProductCode) {
        this.ProductCode = ProductCode;
    }

    public String getProductBarCode() {
        return ProductBarCode;
    }

    public void setProductBarCode(String ProductBarCode) {
        this.ProductBarCode = ProductBarCode;
    }

    public String getProductName() {
        return ProductName;
    }

    public void setProductName(String ProductName) {
        this.ProductName = ProductName;
    }

    public String getProductNameLang1() {
        return ProductNameLang1;
    }

    public void setProductNameLang1(String ProductNameLang1) {
        this.ProductNameLang1 = ProductNameLang1;
    }

    public String getProductNameLang2() {
        return ProductNameLang2;
    }

    public void setProductNameLang2(String ProductNameLang2) {
        this.ProductNameLang2 = ProductNameLang2;
    }

    public String getProductNameLang3() {
        return ProductNameLang3;
    }

    public void setProductNameLang3(String ProductNameLang3) {
        this.ProductNameLang3 = ProductNameLang3;
    }

    public String getProductNameLang4() {
        return ProductNameLang4;
    }

    public void setProductNameLang4(String ProductNameLang4) {
        this.ProductNameLang4 = ProductNameLang4;
    }

    public String getProductNameLang5() {
        return ProductNameLang5;
    }

    public void setProductNameLang5(String ProductNameLang5) {
        this.ProductNameLang5 = ProductNameLang5;
    }

    public String getProductMName() {
        return ProductMName;
    }

    public void setProductMName(String ProductMName) {
        this.ProductMName = ProductMName;
    }

    public String getProductMNameLang1() {
        return ProductMNameLang1;
    }

    public void setProductMNameLang1(String ProductMNameLang1) {
        this.ProductMNameLang1 = ProductMNameLang1;
    }

    public String getProductMNameLang2() {
        return ProductMNameLang2;
    }

    public void setProductMNameLang2(String ProductMNameLang2) {
        this.ProductMNameLang2 = ProductMNameLang2;
    }

    public String getProductMNameLang3() {
        return ProductMNameLang3;
    }

    public void setProductMNameLang3(String ProductMNameLang3) {
        this.ProductMNameLang3 = ProductMNameLang3;
    }

    public String getProductMNameLang4() {
        return ProductMNameLang4;
    }

    public void setProductMNameLang4(String ProductMNameLang4) {
        this.ProductMNameLang4 = ProductMNameLang4;
    }

    public String getProductMNameLang5() {
        return ProductMNameLang5;
    }

    public void setProductMNameLang5(String ProductMNameLang5) {
        this.ProductMNameLang5 = ProductMNameLang5;
    }

    public String getProductPictureServer() {
        return ProductPictureServer;
    }

    public void setProductPictureServer(String ProductPictureServer) {
        this.ProductPictureServer = ProductPictureServer;
    }

    public String getProductPictureClient() {
        return ProductPictureClient;
    }

    public void setProductPictureClient(String ProductPictureClient) {
        this.ProductPictureClient = ProductPictureClient;
    }

    public Integer getPrinterID() {
        return PrinterID;
    }

    public void setPrinterID(Integer PrinterID) {
        this.PrinterID = PrinterID;
    }

    public Integer getPrintGroup() {
        return PrintGroup;
    }

    public void setPrintGroup(Integer PrintGroup) {
        this.PrintGroup = PrintGroup;
    }

    public String getPrintProductName() {
        return PrintProductName;
    }

    public void setPrintProductName(String PrintProductName) {
        this.PrintProductName = PrintProductName;
    }

    public java.util.Date getDurationTime() {
        return DurationTime;
    }

    public void setDurationTime(java.util.Date DurationTime) {
        this.DurationTime = DurationTime;
    }

    public Integer getHasServiceCharge() {
        return HasServiceCharge;
    }

    public void setHasServiceCharge(Integer HasServiceCharge) {
        this.HasServiceCharge = HasServiceCharge;
    }

    public Integer getIsOutOfStock() {
        return IsOutOfStock;
    }

    public void setIsOutOfStock(Integer IsOutOfStock) {
        this.IsOutOfStock = IsOutOfStock;
    }

    public Integer getAutoComment() {
        return AutoComment;
    }

    public void setAutoComment(Integer AutoComment) {
        this.AutoComment = AutoComment;
    }

    public Integer getIsDisplayBill() {
        return IsDisplayBill;
    }

    public void setIsDisplayBill(Integer IsDisplayBill) {
        this.IsDisplayBill = IsDisplayBill;
    }

    public Integer getIsPrintCheck() {
        return IsPrintCheck;
    }

    public void setIsPrintCheck(Integer IsPrintCheck) {
        this.IsPrintCheck = IsPrintCheck;
    }

    public Integer getIsPrintReceipt() {
        return IsPrintReceipt;
    }

    public void setIsPrintReceipt(Integer IsPrintReceipt) {
        this.IsPrintReceipt = IsPrintReceipt;
    }

    public Integer getCanReturnProduct() {
        return CanReturnProduct;
    }

    public void setCanReturnProduct(Integer CanReturnProduct) {
        this.CanReturnProduct = CanReturnProduct;
    }

    public Integer getDisplayAtCheckerSystem() {
        return DisplayAtCheckerSystem;
    }

    public void setDisplayAtCheckerSystem(Integer DisplayAtCheckerSystem) {
        this.DisplayAtCheckerSystem = DisplayAtCheckerSystem;
    }

    public java.util.Date getProductEnableDateTime() {
        return ProductEnableDateTime;
    }

    public void setProductEnableDateTime(java.util.Date ProductEnableDateTime) {
        this.ProductEnableDateTime = ProductEnableDateTime;
    }

    public java.util.Date getProductExpireDateTime() {
        return ProductExpireDateTime;
    }

    public void setProductExpireDateTime(java.util.Date ProductExpireDateTime) {
        this.ProductExpireDateTime = ProductExpireDateTime;
    }

    public java.util.Date getProductEnableDayString() {
        return ProductEnableDayString;
    }

    public void setProductEnableDayString(java.util.Date ProductEnableDayString) {
        this.ProductEnableDayString = ProductEnableDayString;
    }

    public java.util.Date getWarningTime() {
        return WarningTime;
    }

    public void setWarningTime(java.util.Date WarningTime) {
        this.WarningTime = WarningTime;
    }

    public java.util.Date getCriticalTime() {
        return CriticalTime;
    }

    public void setCriticalTime(java.util.Date CriticalTime) {
        this.CriticalTime = CriticalTime;
    }

    public Integer getSaleMode1() {
        return SaleMode1;
    }

    public void setSaleMode1(Integer SaleMode1) {
        this.SaleMode1 = SaleMode1;
    }

    public Integer getSaleMode2() {
        return SaleMode2;
    }

    public void setSaleMode2(Integer SaleMode2) {
        this.SaleMode2 = SaleMode2;
    }

    public Integer getSaleMode3() {
        return SaleMode3;
    }

    public void setSaleMode3(Integer SaleMode3) {
        this.SaleMode3 = SaleMode3;
    }

    public Integer getSaleMode4() {
        return SaleMode4;
    }

    public void setSaleMode4(Integer SaleMode4) {
        this.SaleMode4 = SaleMode4;
    }

    public Integer getSaleMode5() {
        return SaleMode5;
    }

    public void setSaleMode5(Integer SaleMode5) {
        this.SaleMode5 = SaleMode5;
    }

    public Integer getSaleMode6() {
        return SaleMode6;
    }

    public void setSaleMode6(Integer SaleMode6) {
        this.SaleMode6 = SaleMode6;
    }

    public Integer getSaleMode7() {
        return SaleMode7;
    }

    public void setSaleMode7(Integer SaleMode7) {
        this.SaleMode7 = SaleMode7;
    }

    public Integer getSaleMode8() {
        return SaleMode8;
    }

    public void setSaleMode8(Integer SaleMode8) {
        this.SaleMode8 = SaleMode8;
    }

    public Integer getSaleMode9() {
        return SaleMode9;
    }

    public void setSaleMode9(Integer SaleMode9) {
        this.SaleMode9 = SaleMode9;
    }

    public Integer getSaleMode10() {
        return SaleMode10;
    }

    public void setSaleMode10(Integer SaleMode10) {
        this.SaleMode10 = SaleMode10;
    }

    public Integer getVATType() {
        return VATType;
    }

    public void setVATType(Integer VATType) {
        this.VATType = VATType;
    }

    public String getVATCode() {
        return VATCode;
    }

    public void setVATCode(String VATCode) {
        this.VATCode = VATCode;
    }

    public String getProductUnitName() {
        return ProductUnitName;
    }

    public void setProductUnitName(String ProductUnitName) {
        this.ProductUnitName = ProductUnitName;
    }

    public Integer getDiscountAllow() {
        return DiscountAllow;
    }

    public void setDiscountAllow(Integer DiscountAllow) {
        this.DiscountAllow = DiscountAllow;
    }

    public Integer getZeroPriceAllow() {
        return ZeroPriceAllow;
    }

    public void setZeroPriceAllow(Integer ZeroPriceAllow) {
        this.ZeroPriceAllow = ZeroPriceAllow;
    }

    public Integer getLimitDiscountAmount() {
        return LimitDiscountAmount;
    }

    public void setLimitDiscountAmount(Integer LimitDiscountAmount) {
        this.LimitDiscountAmount = LimitDiscountAmount;
    }

    public Integer getLimitDiscountPercent() {
        return LimitDiscountPercent;
    }

    public void setLimitDiscountPercent(Integer LimitDiscountPercent) {
        this.LimitDiscountPercent = LimitDiscountPercent;
    }

    public Integer getCommRate() {
        return CommRate;
    }

    public void setCommRate(Integer CommRate) {
        this.CommRate = CommRate;
    }

    public String getProductDesp() {
        return ProductDesp;
    }

    public void setProductDesp(String ProductDesp) {
        this.ProductDesp = ProductDesp;
    }

    public Integer getProductDisplay() {
        return ProductDisplay;
    }

    public void setProductDisplay(Integer ProductDisplay) {
        this.ProductDisplay = ProductDisplay;
    }

    public Integer getProductActivate() {
        return ProductActivate;
    }

    public void setProductActivate(Integer ProductActivate) {
        this.ProductActivate = ProductActivate;
    }

    public Integer getProductOrdering() {
        return ProductOrdering;
    }

    public void setProductOrdering(Integer ProductOrdering) {
        this.ProductOrdering = ProductOrdering;
    }

    public Integer getPrintOrdering() {
        return PrintOrdering;
    }

    public void setPrintOrdering(Integer PrintOrdering) {
        this.PrintOrdering = PrintOrdering;
    }

    public Integer getAddingFromBranch() {
        return AddingFromBranch;
    }

    public void setAddingFromBranch(Integer AddingFromBranch) {
        this.AddingFromBranch = AddingFromBranch;
    }

    public Integer getDeleted() {
        return Deleted;
    }

    public void setDeleted(Integer Deleted) {
        this.Deleted = Deleted;
    }

    public java.util.Date getInsertDate() {
        return InsertDate;
    }

    public void setInsertDate(java.util.Date InsertDate) {
        this.InsertDate = InsertDate;
    }

    public java.util.Date getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(java.util.Date UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

}
