package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ProductPriceGroupShop.
 */
public class ProductPriceGroupShop {

    private Integer PriceGroupID;
    private Integer ShopID;

    public ProductPriceGroupShop() {
    }

    public ProductPriceGroupShop(Integer PriceGroupID, Integer ShopID) {
        this.PriceGroupID = PriceGroupID;
        this.ShopID = ShopID;
    }

    public Integer getPriceGroupID() {
        return PriceGroupID;
    }

    public void setPriceGroupID(Integer PriceGroupID) {
        this.PriceGroupID = PriceGroupID;
    }

    public Integer getShopID() {
        return ShopID;
    }

    public void setShopID(Integer ShopID) {
        this.ShopID = ShopID;
    }

}
