package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCT_PRICE_GROUP_DATE.
 */
public class ProductPriceGroupDate {

    private int PriceGroupDateID;
    private int PriceGroupID;
    /** Not-null value. */
    private java.util.Date FromDate;
    /** Not-null value. */
    private java.util.Date ToDate;
    private int Deleted;

    public ProductPriceGroupDate() {
    }

    public ProductPriceGroupDate(int PriceGroupDateID, int PriceGroupID) {
        this.PriceGroupDateID = PriceGroupDateID;
        this.PriceGroupID = PriceGroupID;
    }

    public ProductPriceGroupDate(int PriceGroupDateID, int PriceGroupID, java.util.Date FromDate, java.util.Date ToDate, int Deleted) {
        this.PriceGroupDateID = PriceGroupDateID;
        this.PriceGroupID = PriceGroupID;
        this.FromDate = FromDate;
        this.ToDate = ToDate;
        this.Deleted = Deleted;
    }

    public int getPriceGroupDateID() {
        return PriceGroupDateID;
    }

    public void setPriceGroupDateID(int PriceGroupDateID) {
        this.PriceGroupDateID = PriceGroupDateID;
    }

    public int getPriceGroupID() {
        return PriceGroupID;
    }

    public void setPriceGroupID(int PriceGroupID) {
        this.PriceGroupID = PriceGroupID;
    }

    /** Not-null value. */
    public java.util.Date getFromDate() {
        return FromDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFromDate(java.util.Date FromDate) {
        this.FromDate = FromDate;
    }

    /** Not-null value. */
    public java.util.Date getToDate() {
        return ToDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToDate(java.util.Date ToDate) {
        this.ToDate = ToDate;
    }

    public int getDeleted() {
        return Deleted;
    }

    public void setDeleted(int Deleted) {
        this.Deleted = Deleted;
    }

}
