package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STAFFS.
 */
public class Staffs {

    private int StaffID;
    private int StaffRoleID;
    /** Not-null value. */
    private String StaffPassword;
    /** Not-null value. */
    private String StaffCode;
    private Integer StaffGender;
    /** Not-null value. */
    private String StaffFirstName;
    /** Not-null value. */
    private String StaffLastName;
    private String StaffAddress1;
    private String StaffAddress2;
    private String StaffCity;
    private Integer StaffProvince;
    private String StaffZipCode;
    private String StaffTelephone;
    private String StaffMobile;
    private String StaffEmail;
    private java.util.Date StaffBirthDay;
    private String StaffAdditional;
    private String StaffIDNumber;
    private java.util.Date StaffIDIssueDate;
    private java.util.Date StaffIDExpiration;
    private String StaffBlood;
    private String StaffPictureFileServer;
    private String StaffPictureFileClient;
    private Double BasedSalary;
    private Integer LangID;
    private java.util.Date InputDate;
    private Integer InputBy;
    private java.util.Date UpdateDate;
    private Integer UpdateBy;
    private java.util.Date LastUseDate;
    private Integer Activated;
    private Integer Deleted;
    private Integer AddingFromBranch;

    public Staffs() {
    }

    public Staffs(int StaffID) {
        this.StaffID = StaffID;
    }

    public Staffs(int StaffID, int StaffRoleID, String StaffPassword, String StaffCode, Integer StaffGender, String StaffFirstName, String StaffLastName, String StaffAddress1, String StaffAddress2, String StaffCity, Integer StaffProvince, String StaffZipCode, String StaffTelephone, String StaffMobile, String StaffEmail, java.util.Date StaffBirthDay, String StaffAdditional, String StaffIDNumber, java.util.Date StaffIDIssueDate, java.util.Date StaffIDExpiration, String StaffBlood, String StaffPictureFileServer, String StaffPictureFileClient, Double BasedSalary, Integer LangID, java.util.Date InputDate, Integer InputBy, java.util.Date UpdateDate, Integer UpdateBy, java.util.Date LastUseDate, Integer Activated, Integer Deleted, Integer AddingFromBranch) {
        this.StaffID = StaffID;
        this.StaffRoleID = StaffRoleID;
        this.StaffPassword = StaffPassword;
        this.StaffCode = StaffCode;
        this.StaffGender = StaffGender;
        this.StaffFirstName = StaffFirstName;
        this.StaffLastName = StaffLastName;
        this.StaffAddress1 = StaffAddress1;
        this.StaffAddress2 = StaffAddress2;
        this.StaffCity = StaffCity;
        this.StaffProvince = StaffProvince;
        this.StaffZipCode = StaffZipCode;
        this.StaffTelephone = StaffTelephone;
        this.StaffMobile = StaffMobile;
        this.StaffEmail = StaffEmail;
        this.StaffBirthDay = StaffBirthDay;
        this.StaffAdditional = StaffAdditional;
        this.StaffIDNumber = StaffIDNumber;
        this.StaffIDIssueDate = StaffIDIssueDate;
        this.StaffIDExpiration = StaffIDExpiration;
        this.StaffBlood = StaffBlood;
        this.StaffPictureFileServer = StaffPictureFileServer;
        this.StaffPictureFileClient = StaffPictureFileClient;
        this.BasedSalary = BasedSalary;
        this.LangID = LangID;
        this.InputDate = InputDate;
        this.InputBy = InputBy;
        this.UpdateDate = UpdateDate;
        this.UpdateBy = UpdateBy;
        this.LastUseDate = LastUseDate;
        this.Activated = Activated;
        this.Deleted = Deleted;
        this.AddingFromBranch = AddingFromBranch;
    }

    public int getStaffID() {
        return StaffID;
    }

    public void setStaffID(int StaffID) {
        this.StaffID = StaffID;
    }

    public int getStaffRoleID() {
        return StaffRoleID;
    }

    public void setStaffRoleID(int StaffRoleID) {
        this.StaffRoleID = StaffRoleID;
    }

    /** Not-null value. */
    public String getStaffPassword() {
        return StaffPassword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStaffPassword(String StaffPassword) {
        this.StaffPassword = StaffPassword;
    }

    /** Not-null value. */
    public String getStaffCode() {
        return StaffCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStaffCode(String StaffCode) {
        this.StaffCode = StaffCode;
    }

    public Integer getStaffGender() {
        return StaffGender;
    }

    public void setStaffGender(Integer StaffGender) {
        this.StaffGender = StaffGender;
    }

    /** Not-null value. */
    public String getStaffFirstName() {
        return StaffFirstName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStaffFirstName(String StaffFirstName) {
        this.StaffFirstName = StaffFirstName;
    }

    /** Not-null value. */
    public String getStaffLastName() {
        return StaffLastName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStaffLastName(String StaffLastName) {
        this.StaffLastName = StaffLastName;
    }

    public String getStaffAddress1() {
        return StaffAddress1;
    }

    public void setStaffAddress1(String StaffAddress1) {
        this.StaffAddress1 = StaffAddress1;
    }

    public String getStaffAddress2() {
        return StaffAddress2;
    }

    public void setStaffAddress2(String StaffAddress2) {
        this.StaffAddress2 = StaffAddress2;
    }

    public String getStaffCity() {
        return StaffCity;
    }

    public void setStaffCity(String StaffCity) {
        this.StaffCity = StaffCity;
    }

    public Integer getStaffProvince() {
        return StaffProvince;
    }

    public void setStaffProvince(Integer StaffProvince) {
        this.StaffProvince = StaffProvince;
    }

    public String getStaffZipCode() {
        return StaffZipCode;
    }

    public void setStaffZipCode(String StaffZipCode) {
        this.StaffZipCode = StaffZipCode;
    }

    public String getStaffTelephone() {
        return StaffTelephone;
    }

    public void setStaffTelephone(String StaffTelephone) {
        this.StaffTelephone = StaffTelephone;
    }

    public String getStaffMobile() {
        return StaffMobile;
    }

    public void setStaffMobile(String StaffMobile) {
        this.StaffMobile = StaffMobile;
    }

    public String getStaffEmail() {
        return StaffEmail;
    }

    public void setStaffEmail(String StaffEmail) {
        this.StaffEmail = StaffEmail;
    }

    public java.util.Date getStaffBirthDay() {
        return StaffBirthDay;
    }

    public void setStaffBirthDay(java.util.Date StaffBirthDay) {
        this.StaffBirthDay = StaffBirthDay;
    }

    public String getStaffAdditional() {
        return StaffAdditional;
    }

    public void setStaffAdditional(String StaffAdditional) {
        this.StaffAdditional = StaffAdditional;
    }

    public String getStaffIDNumber() {
        return StaffIDNumber;
    }

    public void setStaffIDNumber(String StaffIDNumber) {
        this.StaffIDNumber = StaffIDNumber;
    }

    public java.util.Date getStaffIDIssueDate() {
        return StaffIDIssueDate;
    }

    public void setStaffIDIssueDate(java.util.Date StaffIDIssueDate) {
        this.StaffIDIssueDate = StaffIDIssueDate;
    }

    public java.util.Date getStaffIDExpiration() {
        return StaffIDExpiration;
    }

    public void setStaffIDExpiration(java.util.Date StaffIDExpiration) {
        this.StaffIDExpiration = StaffIDExpiration;
    }

    public String getStaffBlood() {
        return StaffBlood;
    }

    public void setStaffBlood(String StaffBlood) {
        this.StaffBlood = StaffBlood;
    }

    public String getStaffPictureFileServer() {
        return StaffPictureFileServer;
    }

    public void setStaffPictureFileServer(String StaffPictureFileServer) {
        this.StaffPictureFileServer = StaffPictureFileServer;
    }

    public String getStaffPictureFileClient() {
        return StaffPictureFileClient;
    }

    public void setStaffPictureFileClient(String StaffPictureFileClient) {
        this.StaffPictureFileClient = StaffPictureFileClient;
    }

    public Double getBasedSalary() {
        return BasedSalary;
    }

    public void setBasedSalary(Double BasedSalary) {
        this.BasedSalary = BasedSalary;
    }

    public Integer getLangID() {
        return LangID;
    }

    public void setLangID(Integer LangID) {
        this.LangID = LangID;
    }

    public java.util.Date getInputDate() {
        return InputDate;
    }

    public void setInputDate(java.util.Date InputDate) {
        this.InputDate = InputDate;
    }

    public Integer getInputBy() {
        return InputBy;
    }

    public void setInputBy(Integer InputBy) {
        this.InputBy = InputBy;
    }

    public java.util.Date getUpdateDate() {
        return UpdateDate;
    }

    public void setUpdateDate(java.util.Date UpdateDate) {
        this.UpdateDate = UpdateDate;
    }

    public Integer getUpdateBy() {
        return UpdateBy;
    }

    public void setUpdateBy(Integer UpdateBy) {
        this.UpdateBy = UpdateBy;
    }

    public java.util.Date getLastUseDate() {
        return LastUseDate;
    }

    public void setLastUseDate(java.util.Date LastUseDate) {
        this.LastUseDate = LastUseDate;
    }

    public Integer getActivated() {
        return Activated;
    }

    public void setActivated(Integer Activated) {
        this.Activated = Activated;
    }

    public Integer getDeleted() {
        return Deleted;
    }

    public void setDeleted(Integer Deleted) {
        this.Deleted = Deleted;
    }

    public Integer getAddingFromBranch() {
        return AddingFromBranch;
    }

    public void setAddingFromBranch(Integer AddingFromBranch) {
        this.AddingFromBranch = AddingFromBranch;
    }

}
