package com.vtec.j1tth4.vtecpos.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STAFF_ROLE.
 */
public class StaffRole {

    private int StaffRoleID;
    private Integer StaffRoleLevel;
    private String StaffRoleName;
    private Integer Deleted;
    private Integer AddingFromBranch;

    public StaffRole() {
    }

    public StaffRole(int StaffRoleID) {
        this.StaffRoleID = StaffRoleID;
    }

    public StaffRole(int StaffRoleID, Integer StaffRoleLevel, String StaffRoleName, Integer Deleted, Integer AddingFromBranch) {
        this.StaffRoleID = StaffRoleID;
        this.StaffRoleLevel = StaffRoleLevel;
        this.StaffRoleName = StaffRoleName;
        this.Deleted = Deleted;
        this.AddingFromBranch = AddingFromBranch;
    }

    public int getStaffRoleID() {
        return StaffRoleID;
    }

    public void setStaffRoleID(int StaffRoleID) {
        this.StaffRoleID = StaffRoleID;
    }

    public Integer getStaffRoleLevel() {
        return StaffRoleLevel;
    }

    public void setStaffRoleLevel(Integer StaffRoleLevel) {
        this.StaffRoleLevel = StaffRoleLevel;
    }

    public String getStaffRoleName() {
        return StaffRoleName;
    }

    public void setStaffRoleName(String StaffRoleName) {
        this.StaffRoleName = StaffRoleName;
    }

    public Integer getDeleted() {
        return Deleted;
    }

    public void setDeleted(Integer Deleted) {
        this.Deleted = Deleted;
    }

    public Integer getAddingFromBranch() {
        return AddingFromBranch;
    }

    public void setAddingFromBranch(Integer AddingFromBranch) {
        this.AddingFromBranch = AddingFromBranch;
    }

}
